In [1]:
!pip install psycopg2-binary pandas sqlalchemy

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:admin@localhost:5433/financialapi_db"
)

# How many stocks?

In [3]:
query = """
SELECT COUNT(DISTINCT symbol) AS total_stocks
FROM stocks;
"""

df = pd.read_sql(query, engine)
df

   total_stocks
0             5

# stocks มีคอลัมน์อะไรบ้าง

In [16]:
query = """
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'stocks';
"""
pd.read_sql(query, engine)

   column_name
0     stock_id
1  category_id
2       symbol

# List all stock name?

In [17]:
query = """
SELECT DISTINCT symbol
FROM stocks
ORDER BY symbol;
"""

stock_list = pd.read_sql(query, engine)
stock_list

   symbol
0  ADVANC
1     AOT
2    BDMS
3   CPALL
4    GULF

# How many stock categories?

In [18]:
query = """
SELECT COUNT(DISTINCT category_id) AS total_categories
FROM stocks;
"""
pd.read_sql(query, engine)

   total_categories
0                 5

# category มีหุ้นกี่ตัว

In [19]:
query = """
SELECT category_id, COUNT(DISTINCT symbol) AS total_stocks
FROM stocks
GROUP BY category_id
ORDER BY total_stocks DESC;
"""
pd.read_sql(query, engine)

   category_id  total_stocks
0            1             1
1            2             1
2            3             1
3            4             1
4            5             1

# List of categories?

In [20]:
query = """
SELECT category_id, category_name
FROM categories
ORDER BY category_id;
"""
pd.read_sql(query, engine)

   category_id      category_name
0            1             Energy
1            2           Commerce
2            3         Healthcare
3            4  Telecommunication
4            5     Transportation

# stocks + categories หุ้นอะไรอยู่หมวดไหน?

In [13]:
query = """
SELECT
    s.symbol,
    c.category_name
FROM stocks s
JOIN categories c
    ON s.category_id = c.category_id
ORDER BY c.category_name, s.symbol;
"""
pd.read_sql(query, engine)

   symbol      category_name
0   CPALL           Commerce
1    GULF             Energy
2    BDMS         Healthcare
3  ADVANC  Telecommunication
4     AOT     Transportation

# List stock in each catogories?

In [14]:
# มีหุ้นอะไรบ้าง และหุ้นแต่ละตัวถูกจัดอยู่ในหมวดใด
query = """
SELECT 
    c.category_name,
    s.symbol
FROM stocks s
JOIN categories c 
    ON s.category_id = c.category_id
ORDER BY c.category_name, s.symbol;
"""
pd.read_sql(query, engine)

       category_name  symbol
0           Commerce   CPALL
1             Energy    GULF
2         Healthcare    BDMS
3  Telecommunication  ADVANC
4     Transportation     AOT