In [2]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5433/financialapi_db"
)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5433/financialapi_db)

In [5]:
symbols_df = pd.DataFrame({
    "symbol": ["TU"],
    "market": ["SET"] 
})

symbols = symbols_df["symbol"].tolist()

In [7]:
all_data = []

for symbol in symbols:
    try:
        data = market.get_candlestick(
            symbol=symbol,
            interval="1d",
            limit=260
        )

        df = pd.DataFrame(data)
        df["symbol"] = symbol
        df["date"] = pd.to_datetime(df["time"], unit="s")
        all_data.append(df)

        print(f"✅ {symbol} OK")

    except Exception as e:
        print(f"❌ {symbol} error:", e)

# ⚠️ concat เฉพาะตอนที่มีข้อมูล
if all_data:
    prices_df = pd.concat(all_data, ignore_index=True)
else:
    prices_df = pd.DataFrame()

❌ TU error: name 'market' is not defined

In [8]:
!pip install settrade-v2

Requirement already satisfied: settrade-v2 in /opt/anaconda3/lib/python3.13/site-packages (2.2.1)
Requirement already satisfied: requests>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (2.32.5)
Requirement already satisfied: cryptography>=37.0 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (46.0.3)
Requirement already satisfied: betterproto>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.2.5)
Requirement already satisfied: paho-mqtt<2,>=1.6 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.6.1)
Requirement already satisfied: ntplib>=0.4 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (0.4.0)
Requirement already satisfied: typing-extensions>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (4.15.0)
Requirement already satisfied: grpclib in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (0.4.9)
Requirement already satisfied: stringcase in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (1.2.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=37.0->settrade-v2) (2.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=37.0->settrade-v2) (2.23)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2026.1.4)
Requirement already satisfied: h2<5,>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (4.3.0)
Requirement already satisfied: multidict in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (6.7.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (4.1.0)

In [9]:
from settrade_v2 import Investor

investor = Investor(
    app_id="YZ6Qn7ZJWsjSMFNY",
    app_secret="BQ25/nEgRW2r8nJlSXzW4RlZEIlh/XR2mGAbDBnQuNs=",
    app_code="SANDBOX",
    broker_id="SANDBOX"
)

market = investor.MarketData()

In [10]:
symbols_df = pd.DataFrame({
    "symbol": ["TU"],
    "market": ["SET"] 
})

symbols = symbols_df["symbol"].tolist()

In [11]:
all_data = []

for symbol in symbols:
    try:
        data = market.get_candlestick(
            symbol=symbol,
            interval="1d",
            limit=260
        )

        df = pd.DataFrame(data)
        df["symbol"] = symbol
        df["date"] = pd.to_datetime(df["time"], unit="s")
        all_data.append(df)

        print(f"✅ {symbol} OK")

    except Exception as e:
        print(f"❌ {symbol} error:", e)

# ⚠️ concat เฉพาะตอนที่มีข้อมูล
if all_data:
    prices_df = pd.concat(all_data, ignore_index=True)
else:
    prices_df = pd.DataFrame()

❌ TU error: An invalid response was received from the upstream server

In [12]:
import time

for symbol in symbols:
    try:
        data = market.get_candlestick(
            symbol=symbol,
            interval="1d",
            limit=260
        )

        if not data:
            print(f"⚠️ {symbol} no data")
            continue

        df = pd.DataFrame(data)
        df["symbol"] = symbol
        df["date"] = pd.to_datetime(df["time"], unit="s")
        all_data.append(df)

        print(f"✅ {symbol} OK")
        time.sleep(1)  # ⬅️ สำคัญมาก

    except Exception as e:
        print(f"❌ {symbol} error:", e)
        time.sleep(3)  # ⬅️ รอแล้วลองใหม่รอบหน้า

❌ TU error: An invalid response was received from the upstream server

In [15]:
market.get_candlestick(symbol="KBANK", interval="1d", limit=10)

{'lastSequence': 1995880,
 'time': [1772384400],
 'open': [198.0],
 'high': [199.0],
 'low': [197.5],
 'close': [199.0],
 'volume': [1243000],
 'value': [246478700.0]}

In [16]:
all_data = []

for symbol in symbols:
    try:
        data = market.get_candlestick(
            symbol=symbol,
            interval="1d",
            limit=260
        )

        df = pd.DataFrame(data)
        df["symbol"] = symbol
        df["date"] = pd.to_datetime(df["time"], unit="s")
        all_data.append(df)

        print(f"✅ {symbol} OK")

    except Exception as e:
        print(f"❌ {symbol} error:", e)

# ⚠️ concat เฉพาะตอนที่มีข้อมูล
if all_data:
    prices_df = pd.concat(all_data, ignore_index=True)
else:
    prices_df = pd.DataFrame()

✅ TU OK

In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5433/financialapi_db"
)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5433/financialapi_db)

In [2]:
import pandas as pd

pd.read_sql("""
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_name IN ('stocks', 'prices')
ORDER BY table_name, ordinal_position;
""", engine)

   table_name  column_name data_type
0      prices     price_id   integer
1      prices     stock_id   integer
2      prices   trade_date      date
3      prices         open   numeric
4      prices         high   numeric
5      prices          low   numeric
6      prices        close   numeric
7      prices       volume    bigint
8      stocks     stock_id   integer
9      stocks       symbol      text
10     stocks  category_id   integer

In [5]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        INSERT INTO stocks (symbol)
        VALUES
        ('AOT'),
        ('ADVANC'),
        ('BDMS'),
        ('BEM'),
        ('BGRIM'),
        ('BH'),
        ('BJC'),
        ('BTS'),
        ('CBG'),
        ('CPALL'),
        ('CPF'),
        ('CPN'),
        ('CRC'),
        ('DELTA'),
        ('EA'),
        ('GULF'),
        ('INTUCH'),
        ('KBANK'),
        ('KTB'),
        ('PTT')
        ON CONFLICT (symbol) DO NOTHING;
    """))

In [6]:
# ตรวจตาราง Stocks
stocks_df = pd.read_sql("SELECT * FROM stocks;", engine)
stocks_df

    stock_id  symbol  category_id
0          1    GULF          1.0
1          3   CPALL          2.0
2          6    BDMS          3.0
3          7  ADVANC          4.0
4          2     AOT          5.0
5         12     BEM          NaN
6         13   BGRIM          NaN
7         14      BH          NaN
8         15     BJC          NaN
9         16     BTS          NaN
10        17     CBG          NaN
11        19     CPF          NaN
12        20     CPN          NaN
13        21     CRC          NaN
14        22   DELTA          NaN
15        23      EA          NaN
16        25  INTUCH          NaN
17        26   KBANK          NaN
18        27     KTB          NaN
19        28     PTT          NaN

In [8]:
pd.read_sql("SELECT * FROM categories", engine)

   category_id      category_name
0            1             Energy
1            2           Commerce
2            3         Healthcare
3            4  Telecommunication
4            5     Transportation

In [9]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""

    INSERT INTO categories (category_name)
    VALUES
    ('Finance'),
    ('Technology')
    ON CONFLICT DO NOTHING;

    """))

In [10]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""

    UPDATE stocks SET category_id = 5 WHERE symbol='BEM';
    UPDATE stocks SET category_id = 1 WHERE symbol='BGRIM';
    UPDATE stocks SET category_id = 3 WHERE symbol='BH';
    UPDATE stocks SET category_id = 2 WHERE symbol='BJC';
    UPDATE stocks SET category_id = 5 WHERE symbol='BTS';
    UPDATE stocks SET category_id = 2 WHERE symbol='CBG';
    UPDATE stocks SET category_id = 2 WHERE symbol='CPF';
    UPDATE stocks SET category_id = 2 WHERE symbol='CPN';
    UPDATE stocks SET category_id = 2 WHERE symbol='CRC';
    UPDATE stocks SET category_id = 7 WHERE symbol='DELTA';
    UPDATE stocks SET category_id = 1 WHERE symbol='EA';
    UPDATE stocks SET category_id = 4 WHERE symbol='INTUCH';
    UPDATE stocks SET category_id = 6 WHERE symbol='KBANK';
    UPDATE stocks SET category_id = 6 WHERE symbol='KTB';
    UPDATE stocks SET category_id = 1 WHERE symbol='PTT';

    """))

In [11]:
query = """
SELECT s.symbol, c.category_name
FROM stocks s
JOIN categories c
ON s.category_id = c.category_id
ORDER BY s.symbol
"""
pd.read_sql(query, engine)

    symbol      category_name
0   ADVANC  Telecommunication
1      AOT     Transportation
2     BDMS         Healthcare
3      BEM     Transportation
4    BGRIM             Energy
5       BH         Healthcare
6      BJC           Commerce
7      BTS     Transportation
8      CBG           Commerce
9    CPALL           Commerce
10     CPF           Commerce
11     CPN           Commerce
12     CRC           Commerce
13   DELTA         Technology
14      EA             Energy
15    GULF             Energy
16  INTUCH  Telecommunication
17   KBANK            Finance
18     KTB            Finance
19     PTT             Energy

In [12]:
# สร้าง mapping ระหว่าง symbol → stock_id
stock_map = (
    stocks_df
    .set_index("symbol")["stock_id"]
    .to_dict()
)

stock_map

{'GULF': 1,
 'CPALL': 3,
 'BDMS': 6,
 'ADVANC': 7,
 'AOT': 2,
 'BEM': 12,
 'BGRIM': 13,
 'BH': 14,
 'BJC': 15,
 'BTS': 16,
 'CBG': 17,
 'CPF': 19,
 'CPN': 20,
 'CRC': 21,
 'DELTA': 22,
 'EA': 23,
 'INTUCH': 25,
 'KBANK': 26,
 'KTB': 27,
 'PTT': 28}

In [13]:
all_prices = []

for _, row in stocks_df.iterrows():
    
    symbol = row["symbol"]
    stock_id = row["stock_id"]
    
    try:
        df = investor.MarketData.get_candlestick(
            symbol=symbol,
            interval="1d",
            start=start_date.strftime("%Y-%m-%d"),
            end=end_date.strftime("%Y-%m-%d")
        )

        df = pd.DataFrame(df)

        df["stock_id"] = stock_id
        df["symbol"] = symbol

        all_prices.append(df)

        print("Loaded:", symbol)

    except Exception as e:
        print("Error:", symbol)

Error: GULF
Error: CPALL
Error: BDMS
Error: ADVANC
Error: AOT
Error: BEM
Error: BGRIM
Error: BH
Error: BJC
Error: BTS
Error: CBG
Error: CPF
Error: CPN
Error: CRC
Error: DELTA
Error: EA
Error: INTUCH
Error: KBANK
Error: KTB
Error: PTT

In [14]:
from settrade_v2 import Investor

investor = Investor(
    app_id="aVtejKPRDHZ3LE8N",
    app_secret="Z94lVaLw06yYcUWmPFRuroz7H4M5S9rSv/NPHhMLaBM=",
    broker_id="SANDBOX",
    app_code="SANDBOX"
)

In [15]:
market = investor.MarketData()

all_prices = []

for _, row in stocks_df.iterrows():

    symbol = row["symbol"]
    stock_id = row["stock_id"]

    try:

        df = market.get_candlestick(
            symbol=symbol,
            interval="1d"
        )

        df = pd.DataFrame(df)

        df["stock_id"] = stock_id
        df["symbol"] = symbol

        all_prices.append(df)

        print("Loaded:", symbol)

    except Exception as e:

        print("Error:", symbol, e)

Loaded: GULF
Loaded: CPALL
Loaded: BDMS
Loaded: ADVANC
Loaded: AOT
Loaded: BEM
Loaded: BGRIM
Loaded: BH
Loaded: BJC
Loaded: BTS
Loaded: CBG
Loaded: CPF
Loaded: CPN
Loaded: CRC
Loaded: DELTA
Loaded: EA
Error: INTUCH Symbol not found [INTUCH]
Loaded: KBANK
Loaded: KTB
Loaded: PTT

In [16]:
market.get_candlestick(
    symbol="PTT",
    interval="1d"
)

{'lastSequence': 0,
 'time': [1707757200,
  1707843600,
  1707930000,
  1708016400,
  1708275600,
  1708362000,
  1708448400,
  1708534800,
  1708621200,
  1708966800,
  1709053200,
  1709139600,
  1709226000,
  1709485200,
  1709571600,
  1709658000,
  1709744400,
  1709830800,
  1710090000,
  1710176400,
  1710262800,
  1710349200,
  1710435600,
  1710694800,
  1710781200,
  1710867600,
  1710954000,
  1711040400,
  1711299600,
  1711386000,
  1711472400,
  1711558800,
  1711645200,
  1711904400,
  1711990800,
  1712077200,
  1712163600,
  1712250000,
  1712595600,
  1712682000,
  1712768400,
  1713286800,
  1713373200,
  1713459600,
  1713718800,
  1713805200,
  1713891600,
  1713978000,
  1714064400,
  1714323600,
  1714410000,
  1714582800,
  1714669200,
  1715014800,
  1715101200,
  1715187600,
  1715274000,
  1715533200,
  1715619600,
  1715706000,
  1715792400,
  1715878800,
  1716138000,
  1716224400,
  1716397200,
  1716483600,
  1716742800,
  1716829200,
  1716915600,
  1717002000,
  1717088400,
  1717434000,
  1717520400,
  1717606800,
  1717693200,
  1717952400,
  1718038800,
  1718125200,
  1718211600,
  1718298000,
  1718557200,
  1718643600,
  1718730000,
  1718816400,
  1718902800,
  1719162000,
  1719248400,
  1719334800,
  1719421200,
  1719507600,
  1719766800,
  1719853200,
  1719939600,
  1720026000,
  1720112400,
  1720371600,
  1720458000,
  1720544400,
  1720630800,
  1720717200,
  1720976400,
  1721062800,
  1721149200,
  1721235600,
  1721322000,
  1721667600,
  1721754000,
  1721840400,
  1721926800,
  1722272400,
  1722358800,
  1722445200,
  1722531600,
  1722790800,
  1722877200,
  1722963600,
  1723050000,
  1723136400,
  1723482000,
  1723568400,
  1723654800,
  1723741200,
  1724000400,
  1724086800,
  1724173200,
  1724259600,
  1724346000,
  1724605200,
  1724691600,
  1724778000,
  1724864400,
  1724950800,
  1725210000,
  1725296400,
  1725382800,
  1725469200,
  1725555600,
  1725814800,
  1725901200,
  1725987600,
  1726074000,
  1726160400,
  1726419600,
  1726506000,
  1726592400,
  1726678800,
  1726765200,
  1727024400,
  1727110800,
  1727197200,
  1727283600,
  1727370000,
  1727629200,
  1727715600,
  1727802000,
  1727888400,
  1727974800,
  1728234000,
  1728320400,
  1728406800,
  1728493200,
  1728579600,
  1728925200,
  1729011600,
  1729098000,
  1729184400,
  1729443600,
  1729530000,
  1729702800,
  1729789200,
  1730048400,
  1730134800,
  1730221200,
  1730307600,
  1730394000,
  1730653200,
  1730739600,
  1730826000,
  1730912400,
  1730998800,
  1731258000,
  1731344400,
  1731430800,
  1731517200,
  1731603600,
  1731862800,
  1731949200,
  1732035600,
  1732122000,
  1732208400,
  1732467600,
  1732554000,
  1732640400,
  1732726800,
  1732813200,
  1733072400,
  1733158800,
  1733245200,
  1733418000,
  1733677200,
  1733850000,
  1733936400,
  1734022800,
  1734282000,
  1734368400,
  1734454800,
  1734541200,
  1734627600,
  1734886800,
  1734973200,
  1735059600,
  1735146000,
  1735232400,
  1735491600,
  1735750800,
  1735837200,
  1736096400,
  1736182800,
  1736269200,
  1736355600,
  1736442000,
  1736701200,
  1736787600,
  1736874000,
  1736960400,
  1737046800,
  1737306000,
  1737392400,
  1737478800,
  1737565200,
  1737651600,
  1737910800,
  1737997200,
  1738083600,
  1738170000,
  1738256400,
  1738515600,
  1738602000,
  1738688400,
  1738774800,
  1738861200,
  1739120400,
  1739206800,
  1739379600,
  1739466000,
  1739725200,
  1739811600,
  1739898000,
  1739984400,
  1740070800,
  1740330000,
  1740416400,
  1740502800,
  1740589200,
  1740675600,
  1740934800,
  1741021200,
  1741107600,
  1741194000,
  1741280400,
  1741539600,
  1741626000,
  1741712400,
  1741798800,
  1741885200,
  1742144400,
  1742230800,
  1742317200,
  1742403600,
  1742490000,
  1742749200,
  1742835600,
  1742922000,
  1743008400,
  1743094800,
  1743354000,
  1743440400,
  1743526800,
  1743613200,
  1743699600,
  1744045200,
  1744131600,
  1744218000,
  1744304400,
  1744736400,
  1744822800,
  1744909200,
  1745168400,
  1745254800,
  1745341200,
  1745427600,
  1745514000,
  1745773200,
  1745859600,
  1745946000,
  1746118800,
  1746464400,
  1746550800,
  1746637200,
  1746723600,
  1747069200,
  1747155600,
  1747242000,
  1747328400,
  1747587600,
  1747674000,
  1747760400,
  1747846800,
  1747933200,
  1748192400,
  1748278800,
  1748365200,
  1748451600,
  1748538000,
  1748970000,
  1749056400,
  1749142800,
  1749402000,
  1749488400,
  1749574800,
  1749661200,
  1749747600,
  1750006800,
  1750093200,
  1750179600,
  1750266000,
  1750352400,
  1750611600,
  1750698000,
  1750784400,
  1750870800,
  1750957200,
  1751216400,
  1751302800,
  1751389200,
  1751475600,
  1751562000,
  1751821200,
  1751907600,
  1751994000,
  1752166800,
  1752426000,
  1752512400,
  1752598800,
  1752685200,
  1752771600,
  1753030800,
  1753117200,
  1753203600,
  1753290000,
  1753376400,
  1753722000,
  1753808400,
  1753894800,
  1753981200,
  1754240400,
  1754326800,
  1754413200,
  1754499600,
  1754586000,
  1755018000,
  1755104400,
  1755190800,
  1755450000,
  1755536400,
  1755622800,
  1755709200,
  1755795600,
  1756054800,
  1756141200,
  1756227600,
  1756314000,
  1756400400,
  1756659600,
  1756746000,
  1756832400,
  1756918800,
  1757005200,
  1757264400,
  1757350800,
  1757437200,
  1757523600,
  1757610000,
  1757869200,
  1757955600,
  1758042000,
  1758128400,
  1758214800,
  1758474000,
  1758560400,
  1758646800,
  1758733200,
  1758819600,
  1759078800,
  1759165200,
  1759251600,
  1759338000,
  1759424400,
  1759683600,
  1759770000,
  1759856400,
  1759942800,
  1760029200,
  1760374800,
  1760461200,
  1760547600,
  1760634000,
  1760893200,
  1760979600,
  1761066000,
  1761238800,
  1761498000,
  1761584400,
  1761670800,
  1761757200,
  1761843600,
  1762102800,
  1762189200,
  1762275600,
  1762362000,
  1762448400,
  1762707600,
  1762794000,
  1762880400,
  1762966800,
  1763053200,
  1763312400,
  1763398800,
  1763485200,
  1763571600,
  1763658000,
  1763917200,
  1764003600,
  1764090000,
  1764176400,
  1764262800,
  1764522000,
  1764608400,
  1764694800,
  1764781200,
  1765126800,
  1765213200,
  1765386000,
  1765472400,
  1765731600,
  1765818000,
  1765904400,
  1765990800,
  1766077200,
  1766336400,
  1766422800,
  1766509200,
  1766595600,
  1766682000,
  1766941200,
  1767027600,
  1767546000,
  1767632400,
  1767718800,
  1767805200,
  1767891600,
  1768150800,
  1768237200,
  1768323600,
  1768410000,
  1768496400,
  1768755600,
  1768842000,
  1768928400,
  1769014800,
  1769101200,
  1769360400,
  1769446800,
  1769533200,
  1769619600,
  1769706000,
  1769965200,
  1770051600,
  1770138000,
  1770224400,
  1770310800,
  1770570000,
  1770656400,
  1770742800,
  1770829200,
  1770915600,
  1771174800,
  1771261200,
  1771347600,
  1771434000,
  1771520400,
  1771779600,
  1771866000,
  1771952400,
  1772038800,
  1772125200,
  1772384400,
  1772557200,
  1772643600,
  1772730000],
 'open': [35.0,
  34.75,
  34.75,
  35.25,
  35.75,
  35.75,
  35.75,
  35.75,
  35.75,
  35.75,
  35.5,
  34.5,
  34.25,
  34.0,
  34.0,
  34.0,
  34.25,
  34.25,
  33.75,
  34.0,
  33.75,
  34.0,
  34.75,
  34.75,
  34.25,
  34.25,
  34.0,
  34.0,
  34.0,
  33.5,
  33.5,
  33.75,
  33.5,
  34.0,
  33.5,
  34.0,
  34.5,
  34.5,
  34.75,
  35.0,
  35.0,
  34.75,
  34.5,
  34.0,
  33.75,
  33.75,
  34.25,
  33.75,
  34.0,
  33.75,
  33.75,
  33.5,
  33.25,
  33.75,
  33.75,
  33.75,
  33.75,
  33.75,
  33.5,
  33.75,
  33.75,
  34.0,
  33.75,
  34.0,
  33.5,
  33.5,
  33.75,
  33.5,
  33.0,
  32.75,
  33.0,
  32.75,
  32.75,
  32.75,
  32.0,
  32.0,
  32.0,
  32.0,
  32.0,
  31.5,
  31.75,
  31.5,
  32.0,
  32.5,
  32.25,
  32.0,
  32.5,
  32.75,
  32.75,
  32.5,
  32.5,
  32.5,
  32.5,
  32.75,
  33.0,
  33.0,
  33.0,
  33.0,
  33.0,
  32.5,
  32.5,
  32.5,
  32.25,
  32.25,
  32.75,
  32.25,
  32.0,
  31.75,
  32.0,
  31.75,
  31.75,
  32.0,
  31.75,
  31.75,
  31.25,
  31.75,
  31.75,
  32.25,
  33.25,
  34.25,
  33.75,
  34.25,
  34.5,
  34.5,
  34.25,
  34.25,
  34.25,
  34.5,
  34.75,
  33.75,
  33.25,
  33.5,
  33.5,
  33.25,
  33.0,
  33.0,
  34.0,
  34.75,
  34.25,
  33.75,
  33.0,
  33.0,
  32.75,
  33.0,
  33.0,
  33.25,
  33.25,
  33.5,
  33.5,
  33.75,
  33.5,
  33.5,
  33.5,
  33.75,
  34.0,
  33.5,
  33.75,
  34.0,
  34.0,
  33.75,
  33.75,
  34.0,
  34.25,
  33.5,
  33.5,
  33.75,
  34.0,
  34.0,
  33.5,
  33.5,
  33.5,
  34.25,
  33.75,
  33.5,
  33.5,
  33.75,
  33.75,
  33.75,
  33.5,
  33.5,
  33.25,
  33.0,
  33.0,
  32.75,
  32.5,
  32.75,
  32.5,
  32.25,
  32.5,
  33.25,
  33.75,
  33.25,
  32.75,
  32.5,
  32.5,
  32.25,
  32.25,
  32.5,
  32.25,
  32.0,
  32.25,
  32.0,
  31.75,
  31.75,
  32.25,
  32.25,
  32.25,
  31.75,
  31.0,
  31.25,
  31.5,
  31.5,
  31.5,
  31.75,
  31.75,
  31.75,
  32.25,
  32.0,
  32.0,
  31.5,
  31.5,
  31.25,
  31.25,
  30.25,
  31.25,
  31.0,
  31.0,
  31.0,
  31.25,
  31.0,
  30.5,
  30.75,
  30.75,
  31.0,
  31.0,
  31.0,
  31.0,
  31.0,
  30.75,
  30.0,
  30.25,
  30.5,
  30.25,
  30.5,
  30.25,
  31.5,
  31.0,
  31.5,
  31.25,
  31.75,
  32.25,
  32.5,
  32.25,
  32.0,
  31.5,
  31.75,
  31.0,
  30.75,
  29.75,
  29.75,
  29.5,
  28.0,
  28.0,
  27.25,
  27.5,
  29.0,
  29.75,
  29.5,
  29.5,
  31.75,
  31.75,
  32.25,
  32.5,
  32.5,
  32.25,
  32.0,
  32.0,
  31.75,
  31.75,
  31.75,
  30.0,
  30.0,
  31.25,
  30.75,
  31.25,
  31.0,
  31.0,
  31.0,
  30.5,
  30.75,
  30.5,
  30.5,
  30.5,
  30.75,
  30.75,
  31.0,
  31.0,
  30.75,
  31.25,
  31.25,
  31.25,
  31.0,
  31.25,
  31.0,
  31.0,
  31.0,
  31.0,
  30.5,
  30.5,
  30.5,
  30.25,
  30.25,
  30.5,
  30.25,
  30.0,
  29.5,
  30.0,
  30.5,
  29.75,
  30.0,
  30.25,
  30.5,
  31.0,
  30.5,
  30.75,
  30.0,
  30.0,
  30.0,
  30.25,
  30.5,
  30.25,
  30.5,
  30.25,
  30.25,
  30.5,
  30.75,
  30.5,
  30.25,
  30.25,
  30.25,
  30.25,
  30.5,
  30.75,
  31.25,
  31.25,
  31.5,
  32.25,
  32.5,
  32.25,
  32.25,
  31.75,
  32.5,
  33.0,
  33.0,
  33.25,
  32.25,
  32.25,
  32.5,
  32.25,
  32.25,
  32.25,
  32.5,
  32.25,
  32.25,
  32.0,
  31.75,
  31.75,
  32.0,
  32.0,
  32.0,
  32.0,
  31.75,
  31.25,
  31.0,
  31.5,
  31.75,
  32.0,
  31.5,
  31.75,
  31.75,
  32.5,
  32.5,
  33.25,
  33.5,
  33.0,
  33.25,
  33.5,
  33.25,
  33.25,
  33.0,
  33.0,
  33.25,
  33.25,
  33.25,
  33.5,
  32.25,
  32.5,
  32.25,
  32.25,
  32.25,
  32.0,
  32.0,
  32.0,
  31.5,
  31.0,
  31.25,
  30.5,
  30.5,
  31.0,
  30.75,
  31.25,
  31.75,
  31.25,
  30.75,
  30.75,
  31.0,
  30.75,
  30.75,
  30.5,
  30.75,
  30.75,
  30.75,
  30.75,
  30.5,
  30.5,
  30.5,
  30.25,
  30.5,
  30.5,
  30.5,
  30.5,
  30.5,
  30.5,
  30.5,
  30.25,
  30.5,
  30.75,
  31.25,
  31.0,
  31.5,
  31.75,
  31.5,
  31.5,
  31.5,
  31.25,
  31.5,
  31.25,
  31.25,
  31.25,
  31.75,
  32.0,
  31.75,
  31.75,
  31.5,
  31.5,
  31.5,
  31.75,
  31.75,
  31.5,
  31.5,
  31.5,
  31.75,
  32.0,
  32.0,
  32.75,
  32.75,
  33.0,
  33.25,
  33.5,
  33.75,
  33.75,
  33.75,
  33.5,
  34.25,
  34.75,
  34.5,
  34.0,
  34.25,
  34.5,
  34.75,
  35.25,
  35.5,
  35.5,
  35.5,
  35.25,
  35.75,
  35.75,
  35.5,
  35.75,
  36.5,
  37.25,
  37.25,
  36.5,
  37.0,
  37.75,
  37.25,
  37.75,
  36.5,
  34.5,
  34.0],
 'high': [35.25,
  35.0,
  35.0,
  36.0,
  36.0,
  36.0,
  36.0,
  36.25,
  36.0,
  36.0,
  35.75,
  34.75,
  34.5,
  34.25,
  34.25,
  34.5,
  34.5,
  34.25,
  34.0,
  34.25,
  34.25,
  35.0,
  35.0,
  35.0,
  34.5,
  34.5,
  34.25,
  34.5,
  34.25,
  33.75,
  33.75,
  33.75,
  34.0,
  34.0,
  34.0,
  34.75,
  34.75,
  34.75,
  35.0,
  35.25,
  35.25,
  35.0,
  35.0,
  34.25,
  33.75,
  34.25,
  34.25,
  34.0,
  34.25,
  34.0,
  33.75,
  33.75,
  33.75,
  34.0,
  34.0,
  34.0,
  33.75,
  33.75,
  34.0,
  34.0,
  34.0,
  34.0,
  34.25,
  34.0,
  33.75,
  33.75,
  33.75,
  33.5,
  33.25,
  33.0,
  33.25,
  33.25,
  33.0,
  32.75,
  32.25,
  32.25,
  32.5,
  32.25,
  32.0,
  32.0,
  32.0,
  32.25,
  32.5,
  32.5,
  32.25,
  32.5,
  33.0,
  33.0,
  32.75,
  32.75,
  33.0,
  32.75,
  32.75,
  33.0,
  33.0,
  33.0,
  33.25,
  33.25,
  33.25,
  32.75,
  32.75,
  32.75,
  32.5,
  32.75,
  32.75,
  32.5,
  32.25,
  32.0,
  32.0,
  32.0,
  32.25,
  32.25,
  32.25,
  32.0,
  31.75,
  32.0,
  32.25,
  33.5,
  34.25,
  34.5,
  34.0,
  34.5,
  34.75,
  34.5,
  34.25,
  34.5,
  34.75,
  34.75,
  34.75,
  34.0,
  33.5,
  33.75,
  33.5,
  33.5,
  33.25,
  34.0,
  35.0,
  35.0,
  34.5,
  33.75,
  33.5,
  33.25,
  33.25,
  33.25,
  33.5,
  33.5,
  33.75,
  33.5,
  33.75,
  34.0,
  33.75,
  33.75,
  34.0,
  34.0,
  34.0,
  33.75,
  34.0,
  34.0,
  34.0,
  34.0,
  33.75,
  34.75,
  34.25,
  34.0,
  34.0,
  34.0,
  34.0,
  34.0,
  33.75,
  33.75,
  34.25,
  34.5,
  34.0,
  33.75,
  33.75,
  34.0,
  34.25,
  33.75,
  33.75,
  33.75,
  33.5,
  33.25,
  33.25,
  33.0,
  32.75,
  32.75,
  32.75,
  32.5,
  33.25,
  33.75,
  33.75,
  33.5,
  32.75,
  32.75,
  32.75,
  32.25,
  32.5,
  32.75,
  32.5,
  32.25,
  32.5,
  32.25,
  32.0,
  32.5,
  32.25,
  32.5,
  32.5,
  31.75,
  31.25,
  31.5,
  31.75,
  32.0,
  32.0,
  32.0,
  32.0,
  32.0,
  32.5,
  32.0,
  32.0,
  32.0,
  31.75,
  31.5,
  31.25,
  31.25,
  31.5,
  31.25,
  31.0,
  31.25,
  31.5,
  31.25,
  31.0,
  31.25,
  31.25,
  31.25,
  31.0,
  31.75,
  31.0,
  31.25,
  30.75,
  30.5,
  30.75,
  30.75,
  30.75,
  30.75,
  31.0,
  31.5,
  31.5,
  32.0,
  31.75,
  32.25,
  32.5,
  32.75,
  32.5,
  32.5,
  32.0,
  31.75,
  31.25,
  31.25,
  30.25,
  30.0,
  29.75,
  28.25,
  28.25,
  27.75,
  29.25,
  29.5,
  30.0,
  30.0,
  31.25,
  32.0,
  32.25,
  32.5,
  32.75,
  32.75,
  32.5,
  32.25,
  32.25,
  32.25,
  32.25,
  32.25,
  30.75,
  30.5,
  31.75,
  31.5,
  31.5,
  31.25,
  31.5,
  31.0,
  30.75,
  31.0,
  30.75,
  30.5,
  30.75,
  31.0,
  31.0,
  31.25,
  31.25,
  31.5,
  31.5,
  31.25,
  31.75,
  31.25,
  31.25,
  31.25,
  31.25,
  31.0,
  31.0,
  30.75,
  30.75,
  30.75,
  30.5,
  30.5,
  30.5,
  30.5,
  30.0,
  30.0,
  30.5,
  30.5,
  30.0,
  30.5,
  30.75,
  31.25,
  31.0,
  30.75,
  30.75,
  30.25,
  30.5,
  30.25,
  30.5,
  30.5,
  30.75,
  30.75,
  30.5,
  30.75,
  30.75,
  31.0,
  30.75,
  30.5,
  30.5,
  30.5,
  30.75,
  31.0,
  31.25,
  31.5,
  31.75,
  32.25,
  32.5,
  32.5,
  32.5,
  32.5,
  32.5,
  33.0,
  33.5,
  33.75,
  33.5,
  32.5,
  32.5,
  32.5,
  32.5,
  32.5,
  32.5,
  32.5,
  32.5,
  32.5,
  32.25,
  32.0,
  32.25,
  32.25,
  32.25,
  32.25,
  32.0,
  31.75,
  31.5,
  31.5,
  31.75,
  32.25,
  32.25,
  32.0,
  32.25,
  32.5,
  32.75,
  33.5,
  33.5,
  33.5,
  33.25,
  33.75,
  33.5,
  33.5,
  33.5,
  33.25,
  33.25,
  33.5,
  33.5,
  33.75,
  33.5,
  32.5,
  32.5,
  32.5,
  32.25,
  32.25,
  32.25,
  32.0,
  32.0,
  31.5,
  31.25,
  31.25,
  30.75,
  31.0,
  31.25,
  31.25,
  31.75,
  32.0,
  31.5,
  31.25,
  31.25,
  31.0,
  31.25,
  31.0,
  30.75,
  30.75,
  30.75,
  30.75,
  31.0,
  30.75,
  30.75,
  30.75,
  30.75,
  30.75,
  30.5,
  30.75,
  30.5,
  30.5,
  30.5,
  30.5,
  30.5,
  31.0,
  31.25,
  31.5,
  31.5,
  32.0,
  32.0,
  31.75,
  31.5,
  31.5,
  31.75,
  31.75,
  31.5,
  31.5,
  31.75,
  32.0,
  32.25,
  32.0,
  31.75,
  31.75,
  31.75,
  32.0,
  32.0,
  31.75,
  31.75,
  31.75,
  31.75,
  32.0,
  32.25,
  32.75,
  33.0,
  33.25,
  33.25,
  33.75,
  33.75,
  33.75,
  33.75,
  33.75,
  34.25,
  34.75,
  35.0,
  34.5,
  34.25,
  34.75,
  34.75,
  35.25,
  35.5,
  35.75,
  35.75,
  35.75,
  36.25,
  36.0,
  36.0,
  36.0,
  36.25,
  37.5,
  37.75,
  37.25,
  37.0,
  37.75,
  37.75,
  37.75,
  38.0,
  36.5,
  34.75,
  34.5],
 'low': [34.75,
  34.5,
  34.5,
  35.0,
  35.5,
  35.5,
  35.5,
  35.75,
  35.5,
  35.5,
  35.5,
  34.0,
  34.0,
  33.75,
  33.75,
  33.75,
  34.0,
  33.75,
  33.75,
  33.75,
  33.75,
  34.0,
  34.5,
  34.25,
  34.25,
  33.75,
  33.75,
  34.0,
  33.5,
  33.5,
  33.5,
  33.5,
  33.5,
  33.5,
  33.5,
  34.0,
  34.25,
  34.25,
  34.5,
  34.75,
  34.75,
  34.5,
  33.75,
  33.5,
  33.5,
  33.5,
  33.75,
  33.75,
  33.5,
  33.25,
  33.5,
  33.25,
  33.25,
  33.5,
  33.5,
  33.5,
  33.5,
  33.5,
  33.5,
  33.5,
  33.5,
  33.75,
  33.75,
  33.5,
  33.5,
  33.5,
  33.0,
  33.0,
  32.5,
  32.5,
  32.5,
  32.5,
  32.5,
  31.75,
  31.75,
  31.75,
  32.0,
  32.0,
  31.5,
  31.5,
  31.25,
  31.5,
  31.5,
  32.0,
  31.75,
  32.0,
  32.5,
  32.5,
  32.5,
  32.5,
  32.25,
  32.0,
  32.5,
  32.75,
  32.75,
  32.75,
  32.75,
  32.75,
  32.25,
  32.5,
  32.5,
  32.0,
  32.0,
  32.25,
  32.25,
  32.0,
  31.75,
  31.5,
  31.75,
  31.75,
  31.75,
  31.75,
  31.75,
  31.25,
  31.25,
  31.75,
  31.75,
  32.25,
  33.0,
  33.5,
  33.5,
  34.0,
  34.25,
  34.0,
  34.0,
  34.0,
  34.25,
  34.25,
  34.25,
  33.25,
  33.25,
  33.25,
  33.25,
  33.0,
  33.0,
  32.75,
  34.0,
  34.25,
  33.75,
  32.75,
  33.0,
  32.75,
  32.75,
  33.0,
  33.0,
  33.0,
  33.25,
  33.0,
  33.25,
  33.5,
  33.25,
  33.25,
  33.5,
  33.75,
  33.5,
  33.5,
  33.5,
  33.75,
  33.75,
  33.5,
  33.5,
  33.75,
  33.5,
  33.5,
  33.5,
  33.75,
  33.75,
  33.5,
  33.5,
  33.25,
  33.25,
  33.75,
  33.5,
  33.5,
  33.5,
  33.5,
  33.75,
  33.5,
  33.5,
  33.25,
  33.0,
  33.0,
  32.75,
  32.5,
  32.5,
  32.25,
  32.25,
  32.25,
  32.25,
  33.25,
  33.25,
  32.75,
  32.5,
  32.25,
  32.25,
  32.0,
  32.25,
  32.0,
  32.0,
  32.0,
  32.0,
  31.75,
  31.75,
  31.75,
  32.0,
  32.0,
  31.75,
  30.5,
  30.75,
  31.0,
  31.25,
  31.25,
  31.25,
  31.75,
  31.5,
  31.75,
  32.0,
  31.5,
  31.5,
  31.25,
  31.0,
  31.0,
  30.0,
  30.25,
  30.75,
  30.75,
  30.5,
  30.5,
  31.0,
  30.5,
  30.5,
  30.5,
  30.75,
  30.75,
  30.75,
  31.0,
  30.5,
  30.25,
  30.0,
  30.0,
  30.0,
  30.0,
  30.25,
  30.25,
  30.25,
  31.0,
  30.75,
  31.25,
  31.0,
  31.5,
  32.0,
  32.25,
  32.0,
  31.75,
  31.0,
  31.0,
  30.5,
  30.75,
  29.5,
  29.5,
  28.0,
  27.0,
  27.25,
  27.0,
  27.25,
  28.5,
  29.0,
  29.25,
  29.5,
  31.25,
  31.25,
  32.0,
  32.25,
  32.25,
  32.0,
  31.5,
  31.75,
  31.75,
  31.5,
  31.0,
  29.5,
  30.0,
  30.75,
  30.25,
  30.5,
  30.75,
  30.75,
  30.25,
  30.25,
  30.5,
  30.25,
  30.25,
  30.5,
  30.5,
  30.5,
  30.75,
  30.5,
  30.75,
  31.0,
  30.75,
  31.0,
  31.0,
  30.75,
  30.75,
  30.75,
  30.75,
  30.5,
  30.25,
  30.25,
  30.25,
  30.0,
  30.25,
  30.25,
  29.75,
  29.5,
  29.5,
  30.0,
  29.75,
  29.5,
  30.0,
  30.0,
  30.25,
  30.25,
  30.25,
  30.0,
  29.75,
  30.0,
  30.0,
  30.0,
  30.25,
  30.25,
  30.0,
  30.0,
  30.0,
  30.5,
  30.5,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.75,
  31.0,
  31.0,
  31.5,
  32.0,
  32.0,
  32.0,
  31.5,
  31.75,
  32.25,
  33.0,
  32.5,
  32.0,
  32.0,
  32.0,
  32.0,
  32.0,
  31.75,
  32.0,
  32.0,
  32.0,
  31.5,
  31.75,
  31.75,
  31.75,
  31.75,
  32.0,
  31.75,
  31.75,
  31.25,
  31.0,
  30.75,
  31.25,
  31.5,
  31.5,
  31.25,
  31.5,
  31.75,
  32.25,
  32.5,
  33.0,
  32.75,
  32.75,
  33.25,
  32.75,
  32.75,
  32.75,
  32.75,
  32.75,
  33.0,
  33.0,
  33.25,
  33.25,
  32.0,
  32.25,
  32.0,
  32.0,
  32.0,
  31.75,
  31.75,
  31.5,
  31.0,
  31.0,
  30.5,
  30.25,
  30.5,
  30.75,
  30.5,
  31.0,
  31.25,
  30.5,
  30.75,
  30.5,
  30.5,
  30.75,
  30.5,
  30.5,
  30.5,
  30.5,
  30.25,
  30.5,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.0,
  30.25,
  30.25,
  30.25,
  30.5,
  30.5,
  31.0,
  31.0,
  31.25,
  31.5,
  31.25,
  31.0,
  31.0,
  31.25,
  31.25,
  31.0,
  31.0,
  31.0,
  31.5,
  31.75,
  31.5,
  31.5,
  31.25,
  31.25,
  31.5,
  31.5,
  31.5,
  31.5,
  31.5,
  31.5,
  31.75,
  31.75,
  32.0,
  32.25,
  32.75,
  32.75,
  33.0,
  33.25,
  33.25,
  33.5,
  33.5,
  33.5,
  34.25,
  34.25,
  34.0,
  33.75,
  34.25,
  34.25,
  34.5,
  35.0,
  35.0,
  35.25,
  35.25,
  35.25,
  35.5,
  35.5,
  35.5,
  35.75,
  36.5,
  37.0,
  36.5,
  36.25,
  36.75,
  37.0,
  37.0,
  36.75,
  34.25,
  33.25,
  33.5],
 'close': [35.0,
  34.75,
  34.75,
  35.75,
  35.75,
  35.75,
  36.0,
  36.0,
  36.0,
  35.75,
  35.5,
  34.25,
  34.0,
  34.25,
  34.25,
  34.25,
  34.5,
  34.0,
  33.75,
  34.0,
  34.25,
  34.75,
  34.75,

In [17]:
prices_df = pd.concat(all_prices, ignore_index=True)

prices_df.head()

,lastSequence,time,open,high,low,close,volume,value,stock_id,symbol
0,0,1743613200,49.25,50.50,48.75,48.75,89811523,0,1,GULF
1,0,1743699600,48.00,48.25,45.00,45.00,90093986,0,1,GULF
2,0,1744045200,39.00,41.75,38.50,40.00,112546387,0,1,GULF
3,0,1744131600,40.50,43.25,39.75,42.25,92188347,0,1,GULF
4,0,1744218000,45.50,47.50,44.50,46.00,65247520,0,1,GULF

In [18]:
prices_df.shape

(9222, 10)

In [19]:
prices_df.columns

Index(['lastSequence', 'time', 'open', 'high', 'low', 'close', 'volume',
       'value', 'stock_id', 'symbol'],
      dtype='object')

In [20]:
prices_df = prices_df.rename(columns={
    "date":"trade_date"
})

In [23]:
prices_df.to_sql(
    "prices",
    engine,
    if_exists="append",
    index=False
)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "lastSequence" of relation "prices" does not exist
LINE 1: INSERT INTO prices ("lastSequence", time, open, high, low, c...
                            ^

[SQL: INSERT INTO prices ("lastSequence", time, open, high, low, close, volume, value, stock_id, symbol) VALUES (%(lastSequence__0)s, %(time__0)s, %(open__0)s, %(high__0)s, %(low__0)s, %(close__0)s, %(volume__0)s, %(value__0)s, %(stock_id__0)s, %(symbol__0 ... 167654 characters truncated ... , %(low__999)s, %(close__999)s, %(volume__999)s, %(value__999)s, %(stock_id__999)s, %(symbol__999)s)]
[parameters: {'low__0': 48.75, 'open__0': 49.25, 'close__0': 48.75, 'stock_id__0': 1, 'lastSequence__0': 0, 'time__0': 1743613200, 'high__0': 50.5, 'volume__0': 89811523, 'symbol__0': 'GULF', 'value__0': 0, 'low__1': 45.0, 'open__1': 48.0, 'close__1': 45.0, 'stock_id__1': 1, 'lastSequence__1': 0, 'time__1': 1743699600, 'high__1': 48.25, 'volume__1': 90093986, 'symbol__1': 'GULF', 'value__1': 0, 'low__2': 38.5, 'open__2': 39.0, 'close__2': 40.0, 'stock_id__2': 1, 'lastSequence__2': 0, 'time__2': 1744045200, 'high__2': 41.75, 'volume__2': 112546387, 'symbol__2': 'GULF', 'value__2': 0, 'low__3': 39.75, 'open__3': 40.5, 'close__3': 42.25, 'stock_id__3': 1, 'lastSequence__3': 0, 'time__3': 1744131600, 'high__3': 43.25, 'volume__3': 92188347, 'symbol__3': 'GULF', 'value__3': 0, 'low__4': 44.5, 'open__4': 45.5, 'close__4': 46.0, 'stock_id__4': 1, 'lastSequence__4': 0, 'time__4': 1744218000, 'high__4': 47.5, 'volume__4': 65247520, 'symbol__4': 'GULF', 'value__4': 0 ... 9900 parameters truncated ... 'low__995': 22.2, 'open__995': 22.5, 'close__995': 22.2, 'stock_id__995': 6, 'lastSequence__995': 0, 'time__995': 1743008400, 'high__995': 22.7, 'volume__995': 40836769, 'symbol__995': 'BDMS', 'value__995': 0, 'low__996': 22.0, 'open__996': 22.3, 'close__996': 22.2, 'stock_id__996': 6, 'lastSequence__996': 0, 'time__996': 1743094800, 'high__996': 22.3, 'volume__996': 18426926, 'symbol__996': 'BDMS', 'value__996': 0, 'low__997': 21.8, 'open__997': 21.9, 'close__997': 21.8, 'stock_id__997': 6, 'lastSequence__997': 0, 'time__997': 1743354000, 'high__997': 22.3, 'volume__997': 38684786, 'symbol__997': 'BDMS', 'value__997': 0, 'low__998': 22.0, 'open__998': 22.0, 'close__998': 22.1, 'stock_id__998': 6, 'lastSequence__998': 0, 'time__998': 1743440400, 'high__998': 22.3, 'volume__998': 18264203, 'symbol__998': 'BDMS', 'value__998': 0, 'low__999': 22.1, 'open__999': 22.1, 'close__999': 22.5, 'stock_id__999': 6, 'lastSequence__999': 0, 'time__999': 1743526800, 'high__999': 22.5, 'volume__999': 14432969, 'symbol__999': 'BDMS', 'value__999': 0}]
(Background on this error at: https://sqlalche.me/e/20/f405)