In [2]:
pip install settrade-v2

Requirement already satisfied: settrade-v2 in /opt/anaconda3/lib/python3.12/site-packages (2.2.1)
Requirement already satisfied: requests>=2.27 in /opt/anaconda3/lib/python3.12/site-packages (from settrade-v2) (2.32.3)
Requirement already satisfied: cryptography>=37.0 in /opt/anaconda3/lib/python3.12/site-packages (from settrade-v2) (43.0.0)
Requirement already satisfied: betterproto>=1.2 in /opt/anaconda3/lib/python3.12/site-packages (from settrade-v2) (1.2.5)
Requirement already satisfied: paho-mqtt<2,>=1.6 in /opt/anaconda3/lib/python3.12/site-packages (from settrade-v2) (1.6.1)
Requirement already satisfied: ntplib>=0.4 in /opt/anaconda3/lib/python3.12/site-packages (from settrade-v2) (0.4.0)
Requirement already satisfied: typing-extensions>=4.1 in /opt/anaconda3/lib/python3.12/site-packages (from settrade-v2) (4.11.0)
Requirement already satisfied: grpclib in /opt/anaconda3/lib/python3.12/site-packages (from betterproto>=1.2->settrade-v2) (0.4.9)
Requirement already satisfied: stringcase in /opt/anaconda3/lib/python3.12/site-packages (from betterproto>=1.2->settrade-v2) (1.2.0)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.12/site-packages (from cryptography>=37.0->settrade-v2) (1.17.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.27->settrade-v2) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.27->settrade-v2) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.27->settrade-v2) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.27->settrade-v2) (2026.1.4)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.12/site-packages (from cffi>=1.12->cryptography>=37.0->settrade-v2) (2.21)
Requirement already satisfied: h2<5,>=3.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (4.3.0)
Requirement already satisfied: multidict in /opt/anaconda3/lib/python3.12/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (6.0.4)
Requirement already satisfied: hyperframe<7,>=6.1 in /opt/anaconda3/lib/python3.12/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /opt/anaconda3/lib/python3.12/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (4.1.0)
Note: you may need to restart the kernel to use updated packages.

In [7]:
from settrade_v2 import Investor

investor = Investor(
    app_id="yRGqfMWHRZ7Ilsxe",
    app_secret="bUQaPhIceQmA47k4Ns6+ZTrTzLy8rDuQNwAizToPuHU=",
    broker_id="SANDBOX",
    app_code="SANDBOX",
    is_auto_queue=False
)

print("Connected ✅")

Connected ✅

In [9]:
market = investor.MarketData()

In [11]:
bars = market.get_candlestick(
    symbol="PTT",
    interval="1d",
    limit=100
)

print("Rows:", len(bars))
bars[:2]

Rows: 8

KeyError: slice(None, 2, None)

In [13]:
type(bars)
bars

{'lastSequence': 4234060,
 'time': [1759165200,
  1759251600,
  1759338000,
  1759424400,
  1759683600,
  1759770000,
  1759856400,
  1759942800,
  1760029200,
  1760374800,
  1760461200,
  1760547600,
  1760634000,
  1760893200,
  1760979600,
  1761066000,
  1761238800,
  1761498000,
  1761584400,
  1761670800,
  1761757200,
  1761843600,
  1762102800,
  1762189200,
  1762275600,
  1762362000,
  1762448400,
  1762707600,
  1762794000,
  1762880400,
  1762966800,
  1763053200,
  1763312400,
  1763398800,
  1763485200,
  1763571600,
  1763658000,
  1763917200,
  1764003600,
  1764090000,
  1764176400,
  1764262800,
  1764522000,
  1764608400,
  1764694800,
  1764781200,
  1765126800,
  1765213200,
  1765386000,
  1765472400,
  1765731600,
  1765818000,
  1765904400,
  1765990800,
  1766077200,
  1766336400,
  1766422800,
  1766509200,
  1766595600,
  1766682000,
  1766941200,
  1767027600,
  1767546000,
  1767632400,
  1767718800,
  1767805200,
  1767891600,
  1768150800,
  1768237200,
  1768323600,
  1768410000,
  1768496400,
  1768755600,
  1768842000,
  1768928400,
  1769014800,
  1769101200,
  1769360400,
  1769446800,
  1769533200,
  1769619600,
  1769706000,
  1769965200,
  1770051600,
  1770138000,
  1770224400,
  1770310800,
  1770570000,
  1770656400,
  1770742800,
  1770829200,
  1770915600,
  1771174800,
  1771261200,
  1771347600,
  1771434000,
  1771520400,
  1771779600,
  1771866000,
  1771952400],
 'open': [33.5,
  32.25,
  32.5,
  32.25,
  32.25,
  32.25,
  32.0,
  32.0,
  32.0,
  31.5,
  31.0,
  31.25,
  30.5,
  30.5,
  31.0,
  30.75,
  31.25,
  31.75,
  31.25,
  30.75,
  30.75,
  31.0,
  30.75,
  30.75,
  30.5,
  30.75,
  30.75,
  30.75,
  30.75,
  30.5,
  30.5,
  30.5,
  30.25,
  30.5,
  30.5,
  30.5,
  30.5,
  30.5,
  30.5,
  30.5,
  30.25,
  30.5,
  30.75,
  31.25,
  31.0,
  31.5,
  31.75,
  31.5,
  31.5,
  31.5,
  31.25,
  31.5,
  31.25,
  31.25,
  31.25,
  31.75,
  32.0,
  31.75,
  31.75,
  31.5,
  31.5,
  31.5,
  31.75,
  31.75,
  31.5,
  31.5,
  31.5,
  31.75,
  32.0,
  32.0,
  32.75,
  32.75,
  33.0,
  33.25,
  33.5,
  33.75,
  33.75,
  33.75,
  33.5,
  34.25,
  34.75,
  34.5,
  34.0,
  34.25,
  34.5,
  34.75,
  35.25,
  35.5,
  35.5,
  35.5,
  35.25,
  35.75,
  35.75,
  35.5,
  35.75,
  36.5,
  37.25,
  37.25,
  36.5,
  35.5],
 'high': [33.5,
  32.5,
  32.5,
  32.5,
  32.25,
  32.25,
  32.25,
  32.0,
  32.0,
  31.5,
  31.25,
  31.25,
  30.75,
  31.0,
  31.25,
  31.25,
  31.75,
  32.0,
  31.5,
  31.25,
  31.25,
  31.0,
  31.25,
  31.0,
  30.75,
  30.75,
  30.75,
  30.75,
  31.0,
  30.75,
  30.75,
  30.75,
  30.75,
  30.75,
  30.5,
  30.75,
  30.5,
  30.5,
  30.5,
  30.5,
  30.5,
  31.0,
  31.25,
  31.5,
  31.5,
  32.0,
  32.0,
  31.75,
  31.5,
  31.5,
  31.75,
  31.75,
  31.5,
  31.5,
  31.75,
  32.0,
  32.25,
  32.0,
  31.75,
  31.75,
  31.75,
  32.0,
  32.0,
  31.75,
  31.75,
  31.75,
  31.75,
  32.0,
  32.25,
  32.75,
  33.0,
  33.25,
  33.25,
  33.75,
  33.75,
  33.75,
  33.75,
  33.75,
  34.25,
  34.75,
  35.0,
  34.5,
  34.25,
  34.75,
  34.75,
  35.25,
  35.5,
  35.75,
  35.75,
  35.75,
  36.25,
  36.0,
  36.0,
  36.0,
  36.25,
  37.5,
  37.75,
  37.25,
  37.0,
  41.75],
 'low': [33.25,
  32.0,
  32.25,
  32.0,
  32.0,
  32.0,
  31.75,
  31.75,
  31.5,
  31.0,
  31.0,
  30.5,
  30.25,
  30.5,
  30.75,
  30.5,
  31.0,
  31.25,
  30.5,
  30.75,
  30.5,
  30.5,
  30.75,
  30.5,
  30.5,
  30.5,
  30.5,
  30.25,
  30.5,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.25,
  30.0,
  30.25,
  30.25,
  30.25,
  30.5,
  30.5,
  31.0,
  31.0,
  31.25,
  31.5,
  31.25,
  31.0,
  31.0,
  31.25,
  31.25,
  31.0,
  31.0,
  31.0,
  31.5,
  31.75,
  31.5,
  31.5,
  31.25,
  31.25,
  31.5,
  31.5,
  31.5,
  31.5,
  31.5,
  31.5,
  31.75,
  31.75,
  32.0,
  32.25,
  32.75,
  32.75,
  33.0,
  33.25,
  33.25,
  33.5,
  33.5,
  33.5,
  34.25,
  34.25,
  34.0,
  33.75,
  34.25,
  34.25,
  34.5,
  35.0,
  35.0,
  35.25,
  35.25,
  35.25,
  35.5,
  35.5,
  35.5,
  35.75,
  36.5,
  37.0,
  36.5,
  36.25,
  35.25],
 'close': [33.25,
  32.25,
  32.25,
  32.25,
  32.0,
  32.0,
  32.0,
  32.0,
  31.5,
  31.0,
  31.25,
  30.75,
  30.25,
  30.75,
  30.75,
  31.0,
  31.75,
  31.25,
  30.75,
  30.75,
  31.0,
  30.75,
  30.75,
  30.5,
  30.5,
  30.75,
  30.5,
  30.5,
  30.5,
  30.25,
  30.5,
  30.5,
  30.5,
  30.5,
  30.25,
  30.5,
  30.25,
  30.25,
  30.5,
  30.5,
  30.5,
  30.75,
  31.25,
  31.25,
  31.25,
  31.75,
  31.5,
  31.5,
  31.25,
  31.25,
  31.75,
  31.25,
  31.0,
  31.25,
  31.5,
  31.75,
  31.75,
  31.75,
  31.5,
  31.5,
  31.5,
  32.0,
  31.75,
  31.75,
  31.5,
  31.5,
  31.75,
  32.0,
  31.75,
  32.75,
  32.75,
  33.0,
  33.25,
  33.75,
  33.5,
  33.75,
  33.75,
  33.5,
  34.0,
  34.75,
  34.75,
  34.0,
  34.25,
  34.5,
  34.75,
  35.25,
  35.25,
  35.25,
  35.5,
  35.5,
  36.0,
  35.75,
  35.75,
  35.75,
  36.25,
  37.5,
  37.0,
  36.5,
  36.75,
  35.5],
 'volume': [62633553,
  88218295,
  13058366,
  21835061,
  14742097,
  9910257,
  36504878,
  19724440,
  37750818,
  69369703,
  24362702,
  92843756,
  54578068,
  44246633,
  18932252,
  88077182,
  53337168,
  95498464,
  77088279,
  59975783,
  39942256,
  30452946,
  40383126,
  51528351,
  12391851,
  22796722,
  23507286,
  35441262,
  33296655,
  33172024,
  44366765,
  21220076,
  35786336,
  21844883,
  21290982,
  33288752,
  20170947,
  76172223,
  42116897,
  12336732,
  5512777,
  44959261,
  96389105,
  50245556,
  49695179,
  74769359,
  31796006,
  21960708,
  20888463,
  21254004,
  31811966,
  26561266,
  71082325,
  93531188,
  68507371,
  43774425,
  55660625,
  30927077,
  20536806,
  34084620,
  38891304,
  41210512,
  35819490,
  41857471,
  21255014,
  26859351,
  24896792,
  17390781,
  35991074,
  102118165,
  79432534,
  76753911,
  36331495,
  118258708,
  105376780,
  80608123,
  39060051,
  27508910,
  122230841,
  117815693,
  122588227,
  70286946,
  55081904,
  81632736,
  53457668,
  178625163,
  58620929,
  133353862,
  53667605,
  58562132,
  157682951,
  89528683,
  53641360,
  69554357,
  77643087,
  274523921,
  181397687,
  130390094,
  143074741,
  168285100],
 'value': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  6036716450.0]}

In [15]:
import pandas as pd

df = pd.DataFrame({
    'time': bars['time'],
    'open': bars['open'],
    'high': bars['high'],
    'low': bars['low'],
    'close': bars['close'],
    'volume': bars['volume'],
})

df['date'] = pd.to_datetime(df['time'], unit='s')
df = df.sort_values('date')

df.head()

         time   open   high    low  close    volume                date
0  1759165200  33.50  33.50  33.25  33.25  62633553 2025-09-29 17:00:00
1  1759251600  32.25  32.50  32.00  32.25  88218295 2025-09-30 17:00:00
2  1759338000  32.50  32.50  32.25  32.25  13058366 2025-10-01 17:00:00
3  1759424400  32.25  32.50  32.00  32.25  21835061 2025-10-02 17:00:00
4  1759683600  32.25  32.25  32.00  32.00  14742097 2025-10-05 17:00:00

In [17]:
df.head(20)   # ดู 20 แถวแรก

          time   open   high    low  close    volume                date
0   1759165200  33.50  33.50  33.25  33.25  62633553 2025-09-29 17:00:00
1   1759251600  32.25  32.50  32.00  32.25  88218295 2025-09-30 17:00:00
2   1759338000  32.50  32.50  32.25  32.25  13058366 2025-10-01 17:00:00
3   1759424400  32.25  32.50  32.00  32.25  21835061 2025-10-02 17:00:00
4   1759683600  32.25  32.25  32.00  32.00  14742097 2025-10-05 17:00:00
5   1759770000  32.25  32.25  32.00  32.00   9910257 2025-10-06 17:00:00
6   1759856400  32.00  32.25  31.75  32.00  36504878 2025-10-07 17:00:00
7   1759942800  32.00  32.00  31.75  32.00  19724440 2025-10-08 17:00:00
8   1760029200  32.00  32.00  31.50  31.50  37750818 2025-10-09 17:00:00
9   1760374800  31.50  31.50  31.00  31.00  69369703 2025-10-13 17:00:00
10  1760461200  31.00  31.25  31.00  31.25  24362702 2025-10-14 17:00:00
11  1760547600  31.25  31.25  30.50  30.75  92843756 2025-10-15 17:00:00
12  1760634000  30.50  30.75  30.25  30.25  54578068 2025-10-16 17:00:00
13  1760893200  30.50  31.00  30.50  30.75  44246633 2025-10-19 17:00:00
14  1760979600  31.00  31.25  30.75  30.75  18932252 2025-10-20 17:00:00
15  1761066000  30.75  31.25  30.50  31.00  88077182 2025-10-21 17:00:00
16  1761238800  31.25  31.75  31.00  31.75  53337168 2025-10-23 17:00:00
17  1761498000  31.75  32.00  31.25  31.25  95498464 2025-10-26 17:00:00
18  1761584400  31.25  31.50  30.50  30.75  77088279 2025-10-27 17:00:00
19  1761670800  30.75  31.25  30.75  30.75  59975783 2025-10-28 17:00:00

In [19]:
df['date'] = pd.to_datetime(df['time'], unit='s')
df = df.sort_values('date')

df.head()

         time   open   high    low  close    volume                date
0  1759165200  33.50  33.50  33.25  33.25  62633553 2025-09-29 17:00:00
1  1759251600  32.25  32.50  32.00  32.25  88218295 2025-09-30 17:00:00
2  1759338000  32.50  32.50  32.25  32.25  13058366 2025-10-01 17:00:00
3  1759424400  32.25  32.50  32.00  32.25  21835061 2025-10-02 17:00:00
4  1759683600  32.25  32.25  32.00  32.00  14742097 2025-10-05 17:00:00

In [21]:
print(bars['time'])

[1759165200, 1759251600, 1759338000, 1759424400, 1759683600, 1759770000, 1759856400, 1759942800, 1760029200, 1760374800, 1760461200, 1760547600, 1760634000, 1760893200, 1760979600, 1761066000, 1761238800, 1761498000, 1761584400, 1761670800, 1761757200, 1761843600, 1762102800, 1762189200, 1762275600, 1762362000, 1762448400, 1762707600, 1762794000, 1762880400, 1762966800, 1763053200, 1763312400, 1763398800, 1763485200, 1763571600, 1763658000, 1763917200, 1764003600, 1764090000, 1764176400, 1764262800, 1764522000, 1764608400, 1764694800, 1764781200, 1765126800, 1765213200, 1765386000, 1765472400, 1765731600, 1765818000, 1765904400, 1765990800, 1766077200, 1766336400, 1766422800, 1766509200, 1766595600, 1766682000, 1766941200, 1767027600, 1767546000, 1767632400, 1767718800, 1767805200, 1767891600, 1768150800, 1768237200, 1768323600, 1768410000, 1768496400, 1768755600, 1768842000, 1768928400, 1769014800, 1769101200, 1769360400, 1769446800, 1769533200, 1769619600, 1769706000, 1769965200, 1770051600, 1770138000, 1770224400, 1770310800, 1770570000, 1770656400, 1770742800, 1770829200, 1770915600, 1771174800, 1771261200, 1771347600, 1771434000, 1771520400, 1771779600, 1771866000, 1771952400]

In [23]:
import pandas as pd

pd.to_datetime(bars['time'], unit='s')

DatetimeIndex(['2025-09-29 17:00:00', '2025-09-30 17:00:00',
               '2025-10-01 17:00:00', '2025-10-02 17:00:00',
               '2025-10-05 17:00:00', '2025-10-06 17:00:00',
               '2025-10-07 17:00:00', '2025-10-08 17:00:00',
               '2025-10-09 17:00:00', '2025-10-13 17:00:00',
               '2025-10-14 17:00:00', '2025-10-15 17:00:00',
               '2025-10-16 17:00:00', '2025-10-19 17:00:00',
               '2025-10-20 17:00:00', '2025-10-21 17:00:00',
               '2025-10-23 17:00:00', '2025-10-26 17:00:00',
               '2025-10-27 17:00:00', '2025-10-28 17:00:00',
               '2025-10-29 17:00:00', '2025-10-30 17:00:00',
               '2025-11-02 17:00:00', '2025-11-03 17:00:00',
               '2025-11-04 17:00:00', '2025-11-05 17:00:00',
               '2025-11-06 17:00:00', '2025-11-09 17:00:00',
               '2025-11-10 17:00:00', '2025-11-11 17:00:00',
               '2025-11-12 17:00:00', '2025-11-13 17:00:00',
               '2025-11-16 17:00:00', '2025-11-17 17:00:00',
               '2025-11-18 17:00:00', '2025-11-19 17:00:00',
               '2025-11-20 17:00:00', '2025-11-23 17:00:00',
               '2025-11-24 17:00:00', '2025-11-25 17:00:00',
               '2025-11-26 17:00:00', '2025-11-27 17:00:00',
               '2025-11-30 17:00:00', '2025-12-01 17:00:00',
               '2025-12-02 17:00:00', '2025-12-03 17:00:00',
               '2025-12-07 17:00:00', '2025-12-08 17:00:00',
               '2025-12-10 17:00:00', '2025-12-11 17:00:00',
               '2025-12-14 17:00:00', '2025-12-15 17:00:00',
               '2025-12-16 17:00:00', '2025-12-17 17:00:00',
               '2025-12-18 17:00:00', '2025-12-21 17:00:00',
               '2025-12-22 17:00:00', '2025-12-23 17:00:00',
               '2025-12-24 17:00:00', '2025-12-25 17:00:00',
               '2025-12-28 17:00:00', '2025-12-29 17:00:00',
               '2026-01-04 17:00:00', '2026-01-05 17:00:00',
               '2026-01-06 17:00:00', '2026-01-07 17:00:00',
               '2026-01-08 17:00:00', '2026-01-11 17:00:00',
               '2026-01-12 17:00:00', '2026-01-13 17:00:00',
               '2026-01-14 17:00:00', '2026-01-15 17:00:00',
               '2026-01-18 17:00:00', '2026-01-19 17:00:00',
               '2026-01-20 17:00:00', '2026-01-21 17:00:00',
               '2026-01-22 17:00:00', '2026-01-25 17:00:00',
               '2026-01-26 17:00:00', '2026-01-27 17:00:00',
               '2026-01-28 17:00:00', '2026-01-29 17:00:00',
               '2026-02-01 17:00:00', '2026-02-02 17:00:00',
               '2026-02-03 17:00:00', '2026-02-04 17:00:00',
               '2026-02-05 17:00:00', '2026-02-08 17:00:00',
               '2026-02-09 17:00:00', '2026-02-10 17:00:00',
               '2026-02-11 17:00:00', '2026-02-12 17:00:00',
               '2026-02-15 17:00:00', '2026-02-16 17:00:00',
               '2026-02-17 17:00:00', '2026-02-18 17:00:00',
               '2026-02-19 17:00:00', '2026-02-22 17:00:00',
               '2026-02-23 17:00:00', '2026-02-24 17:00:00'],
              dtype='datetime64[ns]', freq=None)

In [25]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="settrade_stock_db",
    user="postgres",
    password="672437002"
)

cur = conn.cursor()

for _, row in df.iterrows():
    cur.execute("""
        INSERT INTO stock_prices 
        (transaction_date, symbol, open_price, high_price, low_price, close_price, volume)
        VALUES (%s,%s,%s,%s,%s,%s,%s)
    """, (
        row['date'].date(),
        "PTT",
        row['open'],
        row['high'],
        row['low'],
        row['close'],
        row['volume']
    ))

conn.commit()

UndefinedTable: relation "stock_prices" does not exist
LINE 2:         INSERT INTO stock_prices
                            ^

In [27]:
cur.execute("""
CREATE TABLE IF NOT EXISTS stock_prices (
    id SERIAL PRIMARY KEY,
    transaction_date DATE,
    symbol VARCHAR(10),
    open_price FLOAT,
    high_price FLOAT,
    low_price FLOAT,
    close_price FLOAT,
    volume BIGINT
);
""")

conn.commit()
print("✅ Table created")

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

In [29]:
conn.rollback()
print("🔄 Transaction reset")

🔄 Transaction reset

In [31]:
cur.execute("""
CREATE TABLE IF NOT EXISTS stock_prices (
    id SERIAL PRIMARY KEY,
    transaction_date DATE,
    symbol VARCHAR(10),
    open_price FLOAT,
    high_price FLOAT,
    low_price FLOAT,
    close_price FLOAT,
    volume BIGINT
);
""")

conn.commit()
print("✅ Table created")

✅ Table created

In [33]:
for _, row in df.iterrows():
    cur.execute("""
        INSERT INTO stock_prices 
        (transaction_date, symbol, open_price, high_price, low_price, close_price, volume)
        VALUES (%s,%s,%s,%s,%s,%s,%s)
    """, (
        row['date'].date(),
        "PTT",
        row['open'],
        row['high'],
        row['low'],
        row['close'],
        row['volume']
    ))

conn.commit()
print("✅ Insert complete")

✅ Insert complete

In [35]:
import pandas as pd

df_check = pd.read_sql("SELECT * FROM stock_prices LIMIT 10", conn)
df_check

/var/folders/s1/d92l8pcd3xj0465l248s42800000gp/T/ipykernel_29642/2614556673.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_check = pd.read_sql("SELECT * FROM stock_prices LIMIT 10", conn)

,id,transaction_date,symbol,open_price,high_price,low_price,close_price,volume
0,1,2025-09-29,PTT,33.50,33.50,33.25,33.25,62633553
1,2,2025-09-30,PTT,32.25,32.50,32.00,32.25,88218295
2,3,2025-10-01,PTT,32.50,32.50,32.25,32.25,13058366
3,4,2025-10-02,PTT,32.25,32.50,32.00,32.25,21835061
4,5,2025-10-05,PTT,32.25,32.25,32.00,32.00,14742097
5,6,2025-10-06,PTT,32.25,32.25,32.00,32.00,9910257
6,7,2025-10-07,PTT,32.00,32.25,31.75,32.00,36504878
7,8,2025-10-08,PTT,32.00,32.00,31.75,32.00,19724440
8,9,2025-10-09,PTT,32.00,32.00,31.50,31.50,37750818
9,10,2025-10-13,PTT,31.50,31.50,31.00,31.00,69369703