In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5433/financialapi_db"
)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5433/financialapi_db)

In [2]:
!pip install settrade-v2

Requirement already satisfied: settrade-v2 in /opt/anaconda3/lib/python3.13/site-packages (2.2.1)
Requirement already satisfied: requests>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (2.32.5)
Requirement already satisfied: cryptography>=37.0 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (46.0.3)
Requirement already satisfied: betterproto>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.2.5)
Requirement already satisfied: paho-mqtt<2,>=1.6 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.6.1)
Requirement already satisfied: ntplib>=0.4 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (0.4.0)
Requirement already satisfied: typing-extensions>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (4.15.0)
Requirement already satisfied: grpclib in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (0.4.9)
Requirement already satisfied: stringcase in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (1.2.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=37.0->settrade-v2) (2.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=37.0->settrade-v2) (2.23)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2026.1.4)
Requirement already satisfied: h2<5,>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (4.3.0)
Requirement already satisfied: multidict in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (6.7.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (4.1.0)

In [3]:
from settrade_v2 import Investor

investor = Investor(
    app_id="2unc2LGVcmUMDI8Q",
    app_secret="bX/KGiq/1kY1E5imbiNiwZpYZErmdTWRUxHzKk+QjVw=",
    app_code="SANDBOX",
    broker_id="SANDBOX"
)

market = investor.MarketData()

In [4]:
# ดึงหุ้น

In [5]:
import pandas as pd
from sqlalchemy import create_engine, text

In [8]:
import pandas as pd

symbols_df = pd.DataFrame({
    "symbol": [
        "24CS","2S","3BBIF","A5","AF","AFC","AHC","AI","AIMCG","AIMIRT","AIRA","AJA","AKS","ALLY","ALPHAX","ALUCON","AMARC","AMATAR","AMC","AMR","ANI","APO","APP","ARIN","ARIP","ARROW","ASN","AXTRART","B52","BAREIT","BC","BCT","BE8","BEAUTY","BEYOND","BGT","BIG","BIOTEC","BJCHI","BKD","BKGI","BKIH","BLC","BLESS","BLISS","BM","BOFFICE","BOL","BPS","BR","BROCK","BRRGIF","BSRC","BTC","BTNC","BTSGIF","BTW","BUI","BVG","B-WORK","CAZ","CCP","CEN","CENTEL","CEYE","CFARM","CFRESH","CGH","CHAO","CHARAN","CHASE","CHIC","CHOTI","CI","CITY","CK","CPANEL","CPAXT","CPH","CPL","CPNCG","CPNREIT","CPR","CPT","CPTREIT","CRANE","CRD","CREDIT","CSC","CSP","CSR","CSS","CTARAF","CTW","CV","D","DCON","DEXON","DHOUSE","DIMET","DITTO","DPAINT","DREIT","DTCENT","DTCI","DUSIT","DV8","EASON","ECF","EE","EFORL","EGATIF","EMC","ESTAR","ETL","EURO","EVER","F&D","FE","FM","FMT","FSX","FTREIT","FUTURERT","GAHREIT","GEL","GENCO","GFC","GJS","GL","GLAND","GLOCON","GLORY","GPI","GREEN","GROREIT","GSTEEL","GTB","GTV","GVREIT","GYT","HEALTH","HFT","HL","HPF","HPT","HTECH","HYDRO","HYDROGEN","I2","ICC","ICN","IIG","III","IMH","IMPACT","IND","INETREIT","INGRS","INOX","INSET","INSURE","IROYAL","ISSARA","ITNS","ITTHI","IVF","JAK","JCKH","JCT","JKN","JPARK","JUBILE","KASET","KBS","KBSPIF","KC","KCAR","KCC","KCG","KCM","KDH","KGEN","KIAT","KISS","KJL","KK","KKC","KLINIQ","KOOL","KPNREIT","KTBSTMR","KTIS","KTMS","KUN","KWC","KWI","KWM","KYE","LALIN","LDC","LEE","LEO","LHHOTEL","LHK","LHRREIT","LHSC","LPH","LRH","LST","LTS","LUXF","MAGURO","MANRIN","MASTER","MATI","MBAX","MCA","M-CHAI","MDX","MEB","MEDEZE","MENA","META","METCO","MFC","MFEC","MGC","MGI","MGT","MICRO","MIDA","MII","MILL","MIPF","MIT","MITSIB","MJD","MJLF","ML","MNIT","MNIT2","MNRF","MODERN","MONO","MOSHI","MOTHER","M-PAT","MPJ","MST","M-STOR","MTI","MTW","MUD","MVP","NAM","NAT","NCAP","NCH","NCP","NDR","NEO","NEP","NFC","NKI","NKT","NL","NOVA","NPK","NTSC","NV","NVD","NWR","OCC","OGC","OHTL","OKJ","ORN","PACO","PAF","PANEL","PAP","PATO","PB","PCC","PCE","PDG","PEACE","PEER","PERM","PHG","PICO","PIMO","PIN","PIS","PJW","PK","PL","PLANET","PLT","PLUS","PMC","PMTA","POLY","POPF","PPPM","PPS","PQS","PRAKIT","PRECHA","PRI","PRIN","PROS","PROSPECT","PROUD","PRTR","PSG","PSP","PSTC","PTC","PTECH","PYLON","Q-CON","QHBREIT","QHHRREIT","QHOP","QLT","QTCG","RABBIT","RAM","READY","RICHY","ROCK","ROCTEC","ROH","RP","RPC","RPH","RSXYZ","RT","RWI","S&J","SA","SAAM","SABUY","SAF","SAFARI","SAFE","SALEE","SANKO","SAT","SAUCE","SAV","SAWANG","SCAP","SCGD","SCI","SCL","SCM","SCP","SDC","SE","SECURE","SE-ED","SEI","SENX","SFLEX","SFT","SGF","SHANG","SIAM","SICT","SIMAT","SINO","SIRIPRT","SJWD","SKE","SKN","SLP","SM","SMART","SMD100","SNPS","SO","SORKON","SPA","SPACK","SPG","SPREME","SPRIME","SPVI","SQ","SRIPANWA","SRS","SSF","SSP","SSPF","SSSC","SST","SSTRT","STANLY","STC","STECH","STELLA","STX","SUC","SUPEREIF","SUTHA","SVR","SVT","SWC","TAKUNI","TAN","TAPAC","TATG","TBN","TCAP","TCC","TCJ","TCMC","TCOAT","TEAMG","TEGH","TEKA","TERA","TFFIF","TGE","TGH","TGPRO","TH","THAI","THANA","THIP","THMUI","THRE","THREL","TIF1","TIGER","TIPH","TITLE","TKC","TLHPF","TLI","TM","TMAN","TMC","TMD","TMI","TMILL","TMT","TMW","TNDT","TNH","TNITY","TNL","TNP","TNPC","TNPF","TNR","TOPP","TPA","TPAC","TPCS","TPL","TPLAS","TPOLY","TPP","TPRIME","TPS","TQM","TQR","TR","TRITN","TRP","TRT","TRU","TRUBB","TRV","TSE","TSI","TSTH","TTI","TTLPF","TTT","TU-PF","TURTLE","TVDH","TVH","TVO","TVT","TWP","TWPC","TWZ","TYCN","UAC","UBA","UBE","UBIS","UEC","UKEM","UMI","UMS","UNIQ","UOBKH","UP","UPF","UPOIC","UREKA","UTP","VARO","VCOM","VGI","VIBHA","VIH","VL","VNG","VPO","VRANDA","VS","WACOAL","WARRIX","WAVE","WELL","WFX","WGE","WHA","WHABT","WHAIR","WHART","WHAUP","WICE","WIIK","WIN","WINDOW","WINMED","WINNER","WORK","WP","WPH","XBIO","XO","XPG","YGG","YONG","YUASA","ZAA"
    ],
})
symbols = symbols_df["symbol"].tolist()

In [9]:
symbols

['24CS',
 '2S',
 '3BBIF',
 'A5',
 'AF',
 'AFC',
 'AHC',
 'AI',
 'AIMCG',
 'AIMIRT',
 'AIRA',
 'AJA',
 'AKS',
 'ALLY',
 'ALPHAX',
 'ALUCON',
 'AMARC',
 'AMATAR',
 'AMC',
 'AMR',
 'ANI',
 'APO',
 'APP',
 'ARIN',
 'ARIP',
 'ARROW',
 'ASN',
 'AXTRART',
 'B52',
 'BAREIT',
 'BC',
 'BCT',
 'BE8',
 'BEAUTY',
 'BEYOND',
 'BGT',
 'BIG',
 'BIOTEC',
 'BJCHI',
 'BKD',
 'BKGI',
 'BKIH',
 'BLC',
 'BLESS',
 'BLISS',
 'BM',
 'BOFFICE',
 'BOL',
 'BPS',
 'BR',
 'BROCK',
 'BRRGIF',
 'BSRC',
 'BTC',
 'BTNC',
 'BTSGIF',
 'BTW',
 'BUI',
 'BVG',
 'B-WORK',
 'CAZ',
 'CCP',
 'CEN',
 'CENTEL',
 'CEYE',
 'CFARM',
 'CFRESH',
 'CGH',
 'CHAO',
 'CHARAN',
 'CHASE',
 'CHIC',
 'CHOTI',
 'CI',
 'CITY',
 'CK',
 'CPANEL',
 'CPAXT',
 'CPH',
 'CPL',
 'CPNCG',
 'CPNREIT',
 'CPR',
 'CPT',
 'CPTREIT',
 'CRANE',
 'CRD',
 'CREDIT',
 'CSC',
 'CSP',
 'CSR',
 'CSS',
 'CTARAF',
 'CTW',
 'CV',
 'D',
 'DCON',
 'DEXON',
 'DHOUSE',
 'DIMET',
 'DITTO',
 'DPAINT',
 'DREIT',
 'DTCENT',
 'DTCI',
 'DUSIT',
 'DV8',
 'EASON',
 'ECF',
 'EE',
 'EFORL',
 'EGATIF',
 'EMC',
 'ESTAR',
 'ETL',
 'EURO',
 'EVER',
 'F&D',
 'FE',
 'FM',
 'FMT',
 'FSX',
 'FTREIT',
 'FUTURERT',
 'GAHREIT',
 'GEL',
 'GENCO',
 'GFC',
 'GJS',
 'GL',
 'GLAND',
 'GLOCON',
 'GLORY',
 'GPI',
 'GREEN',
 'GROREIT',
 'GSTEEL',
 'GTB',
 'GTV',
 'GVREIT',
 'GYT',
 'HEALTH',
 'HFT',
 'HL',
 'HPF',
 'HPT',
 'HTECH',
 'HYDRO',
 'HYDROGEN',
 'I2',
 'ICC',
 'ICN',
 'IIG',
 'III',
 'IMH',
 'IMPACT',
 'IND',
 'INETREIT',
 'INGRS',
 'INOX',
 'INSET',
 'INSURE',
 'IROYAL',
 'ISSARA',
 'ITNS',
 'ITTHI',
 'IVF',
 'JAK',
 'JCKH',
 'JCT',
 'JKN',
 'JPARK',
 'JUBILE',
 'KASET',
 'KBS',
 'KBSPIF',
 'KC',
 'KCAR',
 'KCC',
 'KCG',
 'KCM',
 'KDH',
 'KGEN',
 'KIAT',
 'KISS',
 'KJL',
 'KK',
 'KKC',
 'KLINIQ',
 'KOOL',
 'KPNREIT',
 'KTBSTMR',
 'KTIS',
 'KTMS',
 'KUN',
 'KWC',
 'KWI',
 'KWM',
 'KYE',
 'LALIN',
 'LDC',
 'LEE',
 'LEO',
 'LHHOTEL',
 'LHK',
 'LHRREIT',
 'LHSC',
 'LPH',
 'LRH',
 'LST',
 'LTS',
 'LUXF',
 'MAGURO',
 'MANRIN',
 'MASTER',
 'MATI',
 'MBAX',
 'MCA',
 'M-CHAI',
 'MDX',
 'MEB',
 'MEDEZE',
 'MENA',
 'META',
 'METCO',
 'MFC',
 'MFEC',
 'MGC',
 'MGI',
 'MGT',
 'MICRO',
 'MIDA',
 'MII',
 'MILL',
 'MIPF',
 'MIT',
 'MITSIB',
 'MJD',
 'MJLF',
 'ML',
 'MNIT',
 'MNIT2',
 'MNRF',
 'MODERN',
 'MONO',
 'MOSHI',
 'MOTHER',
 'M-PAT',
 'MPJ',
 'MST',
 'M-STOR',
 'MTI',
 'MTW',
 'MUD',
 'MVP',
 'NAM',
 'NAT',
 'NCAP',
 'NCH',
 'NCP',
 'NDR',
 'NEO',
 'NEP',
 'NFC',
 'NKI',
 'NKT',
 'NL',
 'NOVA',
 'NPK',
 'NTSC',
 'NV',
 'NVD',
 'NWR',
 'OCC',
 'OGC',
 'OHTL',
 'OKJ',
 'ORN',
 'PACO',
 'PAF',
 'PANEL',
 'PAP',
 'PATO',
 'PB',
 'PCC',
 'PCE',
 'PDG',
 'PEACE',
 'PEER',
 'PERM',
 'PHG',
 'PICO',
 'PIMO',
 'PIN',
 'PIS',
 'PJW',
 'PK',
 'PL',
 'PLANET',
 'PLT',
 'PLUS',
 'PMC',
 'PMTA',
 'POLY',
 'POPF',
 'PPPM',
 'PPS',
 'PQS',
 'PRAKIT',
 'PRECHA',
 'PRI',
 'PRIN',
 'PROS',
 'PROSPECT',
 'PROUD',
 'PRTR',
 'PSG',
 'PSP',
 'PSTC',
 'PTC',
 'PTECH',
 'PYLON',
 'Q-CON',
 'QHBREIT',
 'QHHRREIT',
 'QHOP',
 'QLT',
 'QTCG',
 'RABBIT',
 'RAM',
 'READY',
 'RICHY',
 'ROCK',
 'ROCTEC',
 'ROH',
 'RP',
 'RPC',
 'RPH',
 'RSXYZ',
 'RT',
 'RWI',
 'S&J',
 'SA',
 'SAAM',
 'SABUY',
 'SAF',
 'SAFARI',
 'SAFE',
 'SALEE',
 'SANKO',
 'SAT',
 'SAUCE',
 'SAV',
 'SAWANG',
 'SCAP',
 'SCGD',
 'SCI',
 'SCL',
 'SCM',
 'SCP',
 'SDC',
 'SE',
 'SECURE',
 'SE-ED',
 'SEI',
 'SENX',
 'SFLEX',
 'SFT',
 'SGF',
 'SHANG',
 'SIAM',
 'SICT',
 'SIMAT',
 'SINO',
 'SIRIPRT',
 'SJWD',
 'SKE',
 'SKN',
 'SLP',
 'SM',
 'SMART',
 'SMD100',
 'SNPS',
 'SO',
 'SORKON',
 'SPA',
 'SPACK',
 'SPG',
 'SPREME',
 'SPRIME',
 'SPVI',
 'SQ',
 'SRIPANWA',
 'SRS',
 'SSF',
 'SSP',
 'SSPF',
 'SSSC',
 'SST',
 'SSTRT',
 'STANLY',
 'STC',
 'STECH',
 'STELLA',
 'STX',
 'SUC',
 'SUPEREIF',
 'SUTHA',
 'SVR',
 'SVT',
 'SWC',
 'TAKUNI',
 'TAN',
 'TAPAC',
 'TATG',
 'TBN',
 'TCAP',
 'TCC',
 'TCJ',
 'TCMC',
 'TCOAT',
 'TEAMG',
 'TEGH',
 'TEKA',
 'TERA',
 'TFFIF',
 'TGE',
 'TGH',
 'TGPRO',
 'TH',
 'THAI',
 'THANA',
 'THIP',
 'THMUI',
 'THRE',
 'THREL',
 'TIF1',
 'TIGER',
 'TIPH',
 'TITLE',
 'TKC',
 'TLHPF',
 'TLI',
 'TM',
 'TMAN',
 'TMC',
 'TMD',
 'TMI',
 'TMILL',
 'TMT',
 'TMW',
 'TNDT',
 'TNH',
 'TNITY',
 'TNL',
 'TNP',
 'TNPC',
 'TNPF',
 'TNR',
 'TOPP',
 'TPA',
 'TPAC',
 'TPCS',
 'TPL',
 'TPLAS',
 'TPOLY',
 'TPP',
 'TPRIME',
 'TPS',
 'TQM',
 'TQR',
 'TR',
 'TRITN',
 'TRP',
 'TRT',
 'TRU',
 'TRUBB',
 'TRV',
 'TSE',
 'TSI',
 'TSTH',
 'TTI',
 'TTLPF',
 'TTT',
 'TU-PF',
 'TURTLE',
 'TVDH',
 'TVH',
 'TVO',
 'TVT',
 'TWP',
 'TWPC',
 'TWZ',
 'TYCN',
 'UAC',
 'UBA',
 'UBE',
 'UBIS',
 'UEC',
 'UKEM',
 'UMI',
 'UMS',
 'UNIQ',
 'UOBKH',
 'UP',
 'UPF',
 'UPOIC',
 'UREKA',
 'UTP',
 'VARO',
 'VCOM',
 'VGI',
 'VIBHA',
 'VIH',
 'VL',
 'VNG',
 'VPO',
 'VRANDA',
 'VS',
 'WACOAL',
 'WARRIX',
 'WAVE',
 'WELL',
 'WFX',
 'WGE',
 'WHA',
 'WHABT',
 'WHAIR',
 'WHART',
 'WHAUP',
 'WICE',
 'WIIK',
 'WIN',
 'WINDOW',
 'WINMED',
 'WINNER',
 'WORK',
 'WP',
 'WPH',
 'XBIO',
 'XO',
 'XPG',
 'YGG',
 'YONG',
 'YUASA',
 'ZAA']

In [10]:
#ดึงย้อนหลัง

In [11]:
all_data = []

for symbol in symbols:
    try:
        data = market.get_candlestick(
            symbol=symbol,
            interval="1d",
            limit=260
        )

        df = pd.DataFrame(data)
        df["symbol"] = symbol
        df["date"] = pd.to_datetime(df["time"], unit="s")
        all_data.append(df)

        print(f"✅ {symbol} OK")

    except Exception as e:
        print(f"❌ {symbol} error:", e)

# ⚠️ concat เฉพาะตอนที่มีข้อมูล
if all_data:
    prices_df = pd.concat(all_data, ignore_index=True)
else:
    prices_df = pd.DataFrame()

❌ 24CS error: Symbol not found [24CS]
✅ 2S OK
✅ 3BBIF OK
✅ A5 OK
✅ AF OK
✅ AFC OK
✅ AHC OK
✅ AI OK
✅ AIMCG OK
✅ AIMIRT OK
✅ AIRA OK
✅ AJA OK
✅ AKS OK
✅ ALLY OK
✅ ALPHAX OK
✅ ALUCON OK
✅ AMARC OK
✅ AMATAR OK
✅ AMC OK
✅ AMR OK
✅ ANI OK
✅ APO OK
✅ APP OK
✅ ARIN OK
✅ ARIP OK
✅ ARROW OK
✅ ASN OK
✅ AXTRART OK
✅ B52 OK
✅ BAREIT OK
✅ BC OK
✅ BCT OK
✅ BE8 OK
✅ BEAUTY OK
✅ BEYOND OK
✅ BGT OK
✅ BIG OK
✅ BIOTEC OK
✅ BJCHI OK
✅ BKD OK
✅ BKGI OK
✅ BKIH OK
✅ BLC OK
✅ BLESS OK
✅ BLISS OK
✅ BM OK
✅ BOFFICE OK
✅ BOL OK
✅ BPS OK
✅ BR OK
✅ BROCK OK
✅ BRRGIF OK
❌ BSRC error: Symbol not found [BSRC]
✅ BTC OK
✅ BTNC OK
✅ BTSGIF OK
✅ BTW OK
✅ BUI OK
✅ BVG OK
✅ B-WORK OK
✅ CAZ OK
✅ CCP OK
✅ CEN OK
✅ CENTEL OK
✅ CEYE OK
✅ CFARM OK
✅ CFRESH OK
✅ CGH OK
✅ CHAO OK
✅ CHARAN OK
✅ CHASE OK
✅ CHIC OK
✅ CHOTI OK
✅ CI OK
✅ CITY OK
✅ CK OK
✅ CPANEL OK
✅ CPAXT OK
✅ CPH OK
✅ CPL OK
✅ CPNCG OK
✅ CPNREIT OK
✅ CPR OK
✅ CPT OK
✅ CPTREIT OK
✅ CRANE OK
✅ CRD OK
✅ CREDIT OK
✅ CSC OK
✅ CSP OK
✅ CSR OK
✅ CSS OK
✅ CTARAF OK
✅ CTW OK
✅ CV OK
✅ D OK
✅ DCON OK
✅ DEXON OK
✅ DHOUSE OK
✅ DIMET OK
✅ DITTO OK
✅ DPAINT OK
✅ DREIT OK
✅ DTCENT OK
✅ DTCI OK
✅ DUSIT OK
✅ DV8 OK
✅ EASON OK
✅ ECF OK
❌ EE error: Symbol not found [EE]
✅ EFORL OK
✅ EGATIF OK
✅ EMC OK
✅ ESTAR OK
✅ ETL OK
✅ EURO OK
✅ EVER OK
✅ F&D OK
✅ FE OK
✅ FM OK
✅ FMT OK
✅ FSX OK
✅ FTREIT OK
✅ FUTURERT OK
✅ GAHREIT OK
✅ GEL OK
✅ GENCO OK
✅ GFC OK
✅ GJS OK
❌ GL error: Symbol not found [GL]
✅ GLAND OK
❌ GLOCON error: Symbol not found [GLOCON]
✅ GLORY OK
✅ GPI OK
✅ GREEN OK
✅ GROREIT OK
✅ GSTEEL OK
✅ GTB OK
✅ GTV OK
✅ GVREIT OK
✅ GYT OK
✅ HEALTH OK
✅ HFT OK
✅ HL OK
✅ HPF OK
✅ HPT OK
✅ HTECH OK
✅ HYDRO OK
✅ HYDROGEN OK
✅ I2 OK
✅ ICC OK
✅ ICN OK
✅ IIG OK
✅ III OK
✅ IMH OK
✅ IMPACT OK
✅ IND OK
✅ INETREIT OK
✅ INGRS OK
✅ INOX OK
✅ INSET OK
✅ INSURE OK
✅ IROYAL OK
✅ ISSARA OK
✅ ITNS OK
✅ ITTHI OK
✅ IVF OK
✅ JAK OK
❌ JCKH error: Symbol not found [JCKH]
✅ JCT OK
❌ JKN error: Symbol not found [JKN]
✅ JPARK OK
✅ JUBILE OK
✅ KASET OK
✅ KBS OK
✅ KBSPIF OK
✅ KC OK
✅ KCAR OK
✅ KCC OK
✅ KCG OK
✅ KCM OK
✅ KDH OK
✅ KGEN OK
✅ KIAT OK
✅ KISS OK
✅ KJL OK
✅ KK OK
✅ KKC OK
✅ KLINIQ OK
✅ KOOL OK
✅ KPNREIT OK
✅ KTBSTMR OK
✅ KTIS OK
✅ KTMS OK
✅ KUN OK
✅ KWC OK
✅ KWI OK
✅ KWM OK
✅ KYE OK
✅ LALIN OK
✅ LDC OK
✅ LEE OK
✅ LEO OK
✅ LHHOTEL OK
✅ LHK OK
✅ LHRREIT OK
✅ LHSC OK
✅ LPH OK
✅ LRH OK
✅ LST OK
✅ LTS OK
✅ LUXF OK
✅ MAGURO OK
✅ MANRIN OK
✅ MASTER OK
✅ MATI OK
✅ MBAX OK
✅ MCA OK
✅ M-CHAI OK
✅ MDX OK
✅ MEB OK
✅ MEDEZE OK
✅ MENA OK
✅ META OK
✅ METCO OK
✅ MFC OK
✅ MFEC OK
✅ MGC OK
✅ MGI OK
✅ MGT OK
✅ MICRO OK
✅ MIDA OK
✅ MII OK
✅ MILL OK
✅ MIPF OK
❌ MIT error: Symbol not found [MIT]
✅ MITSIB OK
✅ MJD OK
✅ MJLF OK
✅ ML OK
✅ MNIT OK
✅ MNIT2 OK
❌ MNRF error: HTTPSConnectionPool(host='marketapi-test.settrade.com', port=443): Max retries exceeded with url: /api/techchart/v3/098/candlesticks?symbol=MNRF&interval=1d&limit=260 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x175b39d10>, 'Connection to marketapi-test.settrade.com timed out. (connect timeout=None)'))
✅ MODERN OK
✅ MONO OK
✅ MOSHI OK
✅ MOTHER OK
✅ M-PAT OK
✅ MPJ OK
✅ MST OK
✅ M-STOR OK
✅ MTI OK
✅ MTW OK
✅ MUD OK
✅ MVP OK
✅ NAM OK
✅ NAT OK
✅ NCAP OK
✅ NCH OK
✅ NCP OK
✅ NDR OK
✅ NEO OK
✅ NEP OK
✅ NFC OK
✅ NKI OK
✅ NKT OK
✅ NL OK
✅ NOVA OK
✅ NPK OK
✅ NTSC OK
✅ NV OK
✅ NVD OK
✅ NWR OK
✅ OCC OK
✅ OGC OK
✅ OHTL OK
✅ OKJ OK
✅ ORN OK
✅ PACO OK
✅ PAF OK
✅ PANEL OK
✅ PAP OK
✅ PATO OK
✅ PB OK
✅ PCC OK
✅ PCE OK
✅ PDG OK
✅ PEACE OK
✅ PEER OK
✅ PERM OK
✅ PHG OK
✅ PICO OK
✅ PIMO OK
✅ PIN OK
✅ PIS OK
✅ PJW OK
✅ PK OK
✅ PL OK
✅ PLANET OK
✅ PLT OK
✅ PLUS OK
✅ PMC OK
✅ PMTA OK
✅ POLY OK
✅ POPF OK
✅ PPPM OK
✅ PPS OK
✅ PQS OK
✅ PRAKIT OK
✅ PRECHA OK
✅ PRI OK
✅ PRIN OK
✅ PROS OK
✅ PROSPECT OK
✅ PROUD OK
✅ PRTR OK
❌ PSG error: Symbol not found [PSG]
✅ PSP OK
✅ PSTC OK
✅ PTC OK
✅ PTECH OK
✅ PYLON OK
✅ Q-CON OK
✅ QHBREIT OK
✅ QHHRREIT OK
✅ QHOP OK
✅ QLT OK
✅ QTCG OK
✅ RABBIT OK
✅ RAM OK
✅ READY OK
✅ RICHY OK
✅ ROCK OK
✅ ROCTEC OK
✅ ROH OK
✅ RP OK
✅ RPC OK
✅ RPH OK
❌ RSXYZ error: Symbol not found [RSXYZ]
✅ RT OK
✅ RWI OK
✅ S&J OK
✅ SA OK
✅ SAAM OK
❌ SABUY error: Symbol not found [SABUY]
✅ SAF OK
❌ SAFARI error: Symbol not found [SAFARI]
✅ SAFE OK
✅ SALEE OK
✅ SANKO OK
✅ SAT OK
✅ SAUCE OK
✅ SAV OK
✅ SAWANG OK
✅ SCAP OK
✅ SCGD OK
✅ SCI OK
✅ SCL OK
✅ SCM OK
✅ SCP OK
✅ SDC OK
✅ SE OK
✅ SECURE OK
✅ SE-ED OK
✅ SEI OK
✅ SENX OK
✅ SFLEX OK
✅ SFT OK
✅ SGF OK
✅ SHANG OK
✅ SIAM OK
✅ SICT OK
✅ SIMAT OK
✅ SINO OK
✅ SIRIPRT OK
✅ SJWD OK
✅ SKE OK
✅ SKN OK
✅ SLP OK
❌ SM error: Symbol not found [SM]
✅ SMART OK
✅ SMD100 OK
✅ SNPS OK
✅ SO OK
✅ SORKON OK
✅ SPA OK
✅ SPACK OK
✅ SPG OK
✅ SPREME OK
✅ SPRIME OK
✅ SPVI OK
✅ SQ OK
✅ SRIPANWA OK
✅ SRS OK
✅ SSF OK
✅ SSP OK
✅ SSPF OK
✅ SSSC OK
✅ SST OK
✅ SSTRT OK
✅ STANLY OK
✅ STC OK
✅ STECH OK
✅ STELLA OK
✅ STX OK
✅ SUC OK
✅ SUPEREIF OK
✅ SUTHA OK
✅ SVR OK
✅ SVT OK
✅ SWC OK
✅ TAKUNI OK
✅ TAN OK
✅ TAPAC OK
✅ TATG OK
✅ TBN OK
✅ TCAP OK
✅ TCC OK
✅ TCJ OK
✅ TCMC OK
✅ TCOAT OK
✅ TEAMG OK
✅ TEGH OK
✅ TEKA OK
✅ TERA OK
✅ TFFIF OK
✅ TGE OK
✅ TGH OK
✅ TGPRO OK
✅ TH OK
✅ THAI OK
✅ THANA OK
✅ THIP OK
✅ THMUI OK
✅ THRE OK
✅ THREL OK
✅ TIF1 OK
✅ TIGER OK
✅ TIPH OK
✅ TITLE OK
✅ TKC OK
✅ TLHPF OK
✅ TLI OK
✅ TM OK
✅ TMAN OK
✅ TMC OK
✅ TMD OK
✅ TMI OK
✅ TMILL OK
✅ TMT OK
✅ TMW OK
✅ TNDT OK
✅ TNH OK
✅ TNITY OK
✅ TNL OK
✅ TNP OK
✅ TNPC OK
✅ TNPF OK
✅ TNR OK
✅ TOPP OK
✅ TPA OK
✅ TPAC OK
✅ TPCS OK
✅ TPL OK
✅ TPLAS OK
✅ TPOLY OK
✅ TPP OK
✅ TPRIME OK
✅ TPS OK
✅ TQM OK
✅ TQR OK
✅ TR OK
✅ TRITN OK
✅ TRP OK
✅ TRT OK
✅ TRU OK
✅ TRUBB OK
✅ TRV OK
✅ TSE OK
✅ TSI OK
✅ TSTH OK
✅ TTI OK
✅ TTLPF OK
✅ TTT OK
✅ TU-PF OK
✅ TURTLE OK
✅ TVDH OK
✅ TVH OK
✅ TVO OK
✅ TVT OK
✅ TWP OK
✅ TWPC OK
✅ TWZ OK
✅ TYCN OK
✅ UAC OK
✅ UBA OK
✅ UBE OK
✅ UBIS OK
✅ UEC OK
✅ UKEM OK
✅ UMI OK
✅ UMS OK
✅ UNIQ OK
✅ UOBKH OK
✅ UP OK
✅ UPF OK
✅ UPOIC OK
✅ UREKA OK
✅ UTP OK
✅ VARO OK
✅ VCOM OK
✅ VGI OK
✅ VIBHA OK
✅ VIH OK
✅ VL OK
✅ VNG OK
✅ VPO OK
✅ VRANDA OK
✅ VS OK
✅ WACOAL OK
✅ WARRIX OK
✅ WAVE OK
✅ WELL OK
✅ WFX OK
✅ WGE OK
✅ WHA OK
✅ WHABT OK
✅ WHAIR OK
✅ WHART OK
✅ WHAUP OK
✅ WICE OK
❌ WIIK error: HTTPSConnectionPool(host='marketapi-test.settrade.com', port=443): Max retries exceeded with url: /api/techchart/v3/098/candlesticks?symbol=WIIK&interval=1d&limit=260 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x175b3ac10>, 'Connection to marketapi-test.settrade.com timed out. (connect timeout=None)'))
✅ WIN OK
✅ WINDOW OK
✅ WINMED OK
✅ WINNER OK
✅ WORK OK
✅ WP OK
✅ WPH OK
✅ XBIO OK
✅ XO OK
✅ XPG OK
✅ YGG OK
✅ YONG OK
✅ YUASA OK
✅ ZAA OK

In [12]:
# ตรวจสอบ TABLE
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';
"""

tables_df = pd.read_sql(query, engine)
tables_df

   table_name
0      prices
1      stocks
2  categories

In [13]:
#ตรวจ Schema ของ stocks
stocks_schema = pd.read_sql("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'stocks';
""", engine)

stocks_schema

   column_name data_type
0     stock_id   integer
1  category_id   integer
2       symbol      text

In [14]:
#ตรวจ Schema ของ prices
prices_schema = pd.read_sql("""
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'prices';
""", engine)

prices_schema

  column_name data_type
0    price_id   integer
1    stock_id   integer
2  trade_date      date
3        open   numeric
4        high   numeric
5         low   numeric
6       close   numeric
7      volume    bigint

In [20]:
# INSERT

In [21]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5433/financialapi_db"
)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5433/financialapi_db)

In [22]:
# ตรวจตาราง stock and prices
import pandas as pd

pd.read_sql("""
SELECT table_name, column_name, data_type
FROM information_schema.columns
WHERE table_name IN ('stocks', 'prices')
ORDER BY table_name, ordinal_position;
""", engine)

   table_name  column_name data_type
0      prices     price_id   integer
1      prices     stock_id   integer
2      prices   trade_date      date
3      prices         open   numeric
4      prices         high   numeric
5      prices          low   numeric
6      prices        close   numeric
7      prices       volume    bigint
8      stocks     stock_id   integer
9      stocks       symbol      text
10     stocks  category_id   integer

In [23]:
# เช็ค ข้อมูล 
prices_df.head()
prices_df["symbol"].unique(), len(prices_df)

(array(['2S', '3BBIF', 'A5', 'AF', 'AFC', 'AHC', 'AI', 'AIMCG', 'AIMIRT',
        'AIRA', 'AJA', 'AKS', 'ALLY', 'ALPHAX', 'ALUCON', 'AMARC',
        'AMATAR', 'AMC', 'AMR', 'ANI', 'APO', 'APP', 'ARIN', 'ARIP',
        'ARROW', 'ASN', 'AXTRART', 'B52', 'BAREIT', 'BC', 'BCT', 'BE8',
        'BEAUTY', 'BEYOND', 'BGT', 'BIG', 'BIOTEC', 'BJCHI', 'BKD', 'BKGI',
        'BKIH', 'BLC', 'BLESS', 'BM', 'BOFFICE', 'BOL', 'BPS', 'BR',
        'BROCK', 'BRRGIF', 'BTC', 'BTNC', 'BTSGIF', 'BTW', 'BUI', 'BVG',
        'B-WORK', 'CAZ', 'CCP', 'CEN', 'CENTEL', 'CEYE', 'CFARM', 'CFRESH',
        'CGH', 'CHAO', 'CHARAN', 'CHASE', 'CHIC', 'CHOTI', 'CI', 'CITY',
        'CK', 'CPANEL', 'CPAXT', 'CPH', 'CPL', 'CPNCG', 'CPNREIT', 'CPR',
        'CPT', 'CPTREIT', 'CRANE', 'CRD', 'CREDIT', 'CSC', 'CSP', 'CSR',
        'CSS', 'CTARAF', 'CTW', 'CV', 'D', 'DCON', 'DEXON', 'DHOUSE',
        'DIMET', 'DITTO', 'DPAINT', 'DREIT', 'DTCENT', 'DTCI', 'DUSIT',
        'DV8', 'EASON', 'ECF', 'EFORL', 'EGATIF', 'EMC', 'ESTAR', 'ETL',
        'EURO', 'EVER', 'F&D', 'FE', 'FM', 'FMT', 'FSX', 'FTREIT',
        'FUTURERT', 'GAHREIT', 'GEL', 'GENCO', 'GFC', 'GJS', 'GLAND',
        'GLORY', 'GPI', 'GREEN', 'GROREIT', 'GTB', 'GTV', 'GVREIT', 'GYT',
        'HEALTH', 'HFT', 'HL', 'HPF', 'HPT', 'HTECH', 'HYDRO', 'HYDROGEN',
        'I2', 'ICC', 'ICN', 'IIG', 'III', 'IMH', 'IMPACT', 'IND',
        'INETREIT', 'INGRS', 'INOX', 'INSET', 'INSURE', 'IROYAL', 'ISSARA',
        'ITNS', 'ITTHI', 'IVF', 'JAK', 'JCT', 'JPARK', 'JUBILE', 'KASET',
        'KBS', 'KBSPIF', 'KC', 'KCAR', 'KCC', 'KCG', 'KCM', 'KDH', 'KGEN',
        'KIAT', 'KISS', 'KJL', 'KK', 'KKC', 'KLINIQ', 'KOOL', 'KPNREIT',
        'KTBSTMR', 'KTIS', 'KTMS', 'KUN', 'KWC', 'KWI', 'KWM', 'KYE',
        'LALIN', 'LDC', 'LEE', 'LEO', 'LHHOTEL', 'LHK', 'LHRREIT', 'LHSC',
        'LPH', 'LRH', 'LST', 'LTS', 'LUXF', 'MAGURO', 'MANRIN', 'MASTER',
        'MATI', 'MBAX', 'MCA', 'M-CHAI', 'MDX', 'MEB', 'MEDEZE', 'MENA',
        'META', 'METCO', 'MFC', 'MFEC', 'MGC', 'MGI', 'MGT', 'MICRO',
        'MIDA', 'MII', 'MILL', 'MIPF', 'MITSIB', 'MJD', 'MJLF', 'ML',
        'MNIT', 'MNIT2', 'MODERN', 'MONO', 'MOSHI', 'MOTHER', 'M-PAT',
        'MPJ', 'MST', 'M-STOR', 'MTI', 'MTW', 'MUD', 'MVP', 'NAM', 'NAT',
        'NCAP', 'NCH', 'NCP', 'NDR', 'NEO', 'NEP', 'NFC', 'NKI', 'NKT',
        'NL', 'NOVA', 'NPK', 'NTSC', 'NV', 'NVD', 'NWR', 'OCC', 'OGC',
        'OHTL', 'OKJ', 'ORN', 'PACO', 'PAF', 'PANEL', 'PAP', 'PATO', 'PB',
        'PCC', 'PCE', 'PDG', 'PEACE', 'PEER', 'PERM', 'PHG', 'PICO',
        'PIMO', 'PIN', 'PIS', 'PJW', 'PK', 'PL', 'PLANET', 'PLT', 'PLUS',
        'PMC', 'PMTA', 'POLY', 'POPF', 'PPPM', 'PPS', 'PQS', 'PRAKIT',
        'PRECHA', 'PRI', 'PRIN', 'PROS', 'PROSPECT', 'PROUD', 'PRTR',
        'PSP', 'PSTC', 'PTC', 'PTECH', 'PYLON', 'Q-CON', 'QHBREIT',
        'QHHRREIT', 'QHOP', 'QLT', 'QTCG', 'RABBIT', 'RAM', 'READY',
        'RICHY', 'ROCK', 'ROCTEC', 'ROH', 'RP', 'RPC', 'RPH', 'RT', 'RWI',
        'S&J', 'SA', 'SAAM', 'SAF', 'SAFE', 'SALEE', 'SANKO', 'SAT',
        'SAUCE', 'SAV', 'SAWANG', 'SCAP', 'SCGD', 'SCI', 'SCL', 'SCM',
        'SCP', 'SDC', 'SE', 'SECURE', 'SE-ED', 'SEI', 'SENX', 'SFLEX',
        'SFT', 'SGF', 'SHANG', 'SIAM', 'SICT', 'SIMAT', 'SINO', 'SIRIPRT',
        'SJWD', 'SKE', 'SKN', 'SLP', 'SMART', 'SMD100', 'SNPS', 'SO',
        'SORKON', 'SPA', 'SPACK', 'SPG', 'SPREME', 'SPRIME', 'SPVI', 'SQ',
        'SRIPANWA', 'SRS', 'SSF', 'SSP', 'SSPF', 'SSSC', 'SST', 'SSTRT',
        'STANLY', 'STC', 'STECH', 'STELLA', 'STX', 'SUC', 'SUPEREIF',
        'SUTHA', 'SVR', 'SVT', 'SWC', 'TAKUNI', 'TAN', 'TAPAC', 'TATG',
        'TBN', 'TCAP', 'TCC', 'TCJ', 'TCMC', 'TCOAT', 'TEAMG', 'TEGH',
        'TEKA', 'TERA', 'TFFIF', 'TGE', 'TGH', 'TGPRO', 'TH', 'THAI',
        'THANA', 'THIP', 'THMUI', 'THRE', 'THREL', 'TIF1', 'TIGER', 'TIPH',
        'TITLE', 'TKC', 'TLHPF', 'TLI', 'TM', 'TMAN', 'TMC', 'TMD', 'TMI',
        'TMILL', 'TMT', 'TMW', 'TNDT', 'TNH', 'TNITY', 'TNL', 'TNP',
        'TNPC', 'TNPF', 'TNR', 'TOPP', 'TPA', 'TPAC', 'TPCS', 'TPL',
        'TPLAS', 'TPOLY', 'TPP', 'TPRIME', 'TPS', 'TQM', 'TQR', 'TR',
        'TRITN', 'TRP', 'TRT', 'TRU', 'TRUBB', 'TRV', 'TSE', 'TSI', 'TSTH',
        'TTI', 'TTLPF', 'TTT', 'TU-PF', 'TURTLE', 'TVDH', 'TVH', 'TVO',
        'TVT', 'TWP', 'TWPC', 'TWZ', 'TYCN', 'UAC', 'UBA', 'UBE', 'UBIS',
        'UEC', 'UKEM', 'UMI', 'UMS', 'UNIQ', 'UOBKH', 'UP', 'UPF', 'UPOIC',
        'UREKA', 'UTP', 'VARO', 'VCOM', 'VGI', 'VIBHA', 'VIH', 'VL', 'VNG',
        'VPO', 'VRANDA', 'VS', 'WACOAL', 'WARRIX', 'WAVE', 'WFX', 'WGE',
        'WHA', 'WHABT', 'WHAIR', 'WHART', 'WHAUP', 'WICE', 'WIN', 'WINDOW',
        'WINMED', 'WINNER', 'WORK', 'WP', 'WPH', 'XBIO', 'XO', 'XPG',
        'YGG', 'YONG', 'YUASA', 'ZAA'], dtype=object),
 136572)

In [24]:
# เตรียม DataFrame สำหรับตาราง stocks
stocks_df = (
    prices_df[["symbol"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

stocks_df

    symbol
0       2S
1    3BBIF
2       A5
3       AF
4      AFC
..     ...
523    XPG
524    YGG
525   YONG
526  YUASA
527    ZAA

[528 rows x 1 columns]

In [25]:
# INSERT หุ้นเข้า table stocks
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in stocks_df.iterrows():
        conn.execute(
            text("""
                INSERT INTO stocks (symbol)
                VALUES (:symbol)
                ON CONFLICT (symbol) DO NOTHING
            """),
            {"symbol": row["symbol"]}
        )

In [26]:
# ดึง stock_id ออกมา map
stocks_map = pd.read_sql(
    "SELECT stock_id, symbol FROM stocks;",
    engine
)

stocks_map

     stock_id symbol
0         395     2S
1         396  3BBIF
2         397     A5
3         398     AF
4         399    AFC
..        ...    ...
865       917     XO
866       919    YGG
867       920   YONG
868       921  YUASA
869       922    ZAA

[870 rows x 2 columns]

In [31]:
#merge stock_id เข้า prices_df
prices_df = prices_df.merge(
    stocks_map,
    on="symbol",
    how="left"
)

prices_df.head()

,lastSequence,time,open,high,low,close,volume,value,symbol,date,stock_id_x,stock_id_y,stock_id
0,2306562,1.741194e+09,2.26,2.26,2.20,2.26,48974.0,0.0,2S,2025-03-05 17:00:00,395,395,395
1,2306562,1.741280e+09,2.14,2.20,2.10,2.18,82189.0,0.0,2S,2025-03-06 17:00:00,395,395,395
2,2306562,1.741540e+09,2.12,2.16,2.12,2.16,329118.0,0.0,2S,2025-03-09 17:00:00,395,395,395
3,2306562,1.741626e+09,2.18,2.22,2.14,2.20,126722.0,0.0,2S,2025-03-10 17:00:00,395,395,395
4,2306562,1.741712e+09,2.18,2.22,2.16,2.20,35230.0,0.0,2S,2025-03-11 17:00:00,395,395,395

In [32]:
#เตรียมคอลัมน์ให้ตรง table prices
prices_insert_df = prices_df[[
    "stock_id",
    "date",
    "open",
    "high",
    "low",
    "close",
    "volume"
]].rename(columns={"date": "trade_date"})

prices_insert_df.head()

   stock_id          trade_date  open  high   low  close    volume
0       395 2025-03-05 17:00:00  2.26  2.26  2.20   2.26   48974.0
1       395 2025-03-06 17:00:00  2.14  2.20  2.10   2.18   82189.0
2       395 2025-03-09 17:00:00  2.12  2.16  2.12   2.16  329118.0
3       395 2025-03-10 17:00:00  2.18  2.22  2.14   2.20  126722.0
4       395 2025-03-11 17:00:00  2.18  2.22  2.16   2.20   35230.0

In [33]:
#INSERT ข้อมูลย้อนหลังทั้งหมดลง prices
prices_insert_df.to_sql(
    "prices",
    engine,
    if_exists="append",
    index=False,
    method="multi",
    chunksize=1000
)

136572

In [34]:
#ตรวจสอบผลลัพธ์ 
pd.read_sql("SELECT COUNT(*) FROM prices;", engine)

    count
0  232909

In [35]:
pd.read_sql("""
SELECT
    s.symbol,
    MIN(p.trade_date) AS start_date,
    MAX(p.trade_date) AS end_date,
    COUNT(*) AS records
FROM prices p
JOIN stocks s ON p.stock_id = s.stock_id
GROUP BY s.symbol
ORDER BY s.symbol;
""", engine)

    symbol  start_date    end_date  records
0       2S  2025-03-05  2026-04-02      260
1    3BBIF  2025-03-05  2026-04-02      260
2        A  2024-10-10  2026-02-25      260
3       A5  2025-02-27  2026-04-02      260
4      AAI  2025-02-25  2026-03-23      260
..     ...         ...         ...      ...
864    YGG  2025-03-05  2026-04-02      260
865   YONG  2025-03-05  2026-04-02      260
866  YUASA  2025-03-05  2026-04-02      260
867    ZAA  2025-02-26  2026-04-02      260
868    ZEN  2025-01-13  2026-03-22      260

[869 rows x 4 columns]

In [36]:
conn.rollback()

In [37]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="financialapi_db",
    user="postgres",
    password="admin",
    port="5433"
)

cur = conn.cursor()

# 🔥 แก้ปัญหา transaction ค้าง
conn.rollback()

cur.execute("""
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public';
""")

print(cur.fetchall())

cur.close()
conn.close()

[('prices',), ('stocks',), ('categories',)]

In [38]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="financialapi_db",
    user="postgres",
    password="admin",
    port="5433"
)

cur = conn.cursor()

query = """
SELECT 
  (SELECT COUNT(*) FROM stocks),
  (SELECT COUNT(*) FROM prices),
  (SELECT COUNT(*) FROM categories);
"""

cur.execute(query)
result = cur.fetchone()

print(f"stocks: {result[0]}")
print(f"prices: {result[1]}")
print(f"category: {result[2]}")

cur.close()
conn.close()

stocks: 870
prices: 232909
category: 9

In [39]:
pd.read_sql("SELECT * FROM stocks WHERE category_id IS NULL;", engine)

     stock_id symbol category_id
0         395     2S        None
1         396  3BBIF        None
2         397     A5        None
3         398     AF        None
4         399    AFC        None
..        ...    ...         ...
498       917     XO        None
499       919    YGG        None
500       920   YONG        None
501       921  YUASA        None
502       922    ZAA        None

[503 rows x 3 columns]

In [40]:
missing = pd.read_sql(
    "SELECT * FROM stocks WHERE category_id IS NULL;",
    engine
)

missing.head()

   stock_id symbol category_id
0       395     2S        None
1       396  3BBIF        None
2       397     A5        None
3       398     AF        None
4       399    AFC        None

In [44]:
def classify(symbol):
    symbol = symbol.upper()

    for category, keywords in CATEGORY_RULES.items():
        if any(k in symbol for k in keywords):
            return category

    return "Other"

In [45]:
# เตรียม rule (กฎการจัดหมวด) Category
CATEGORY_RULES = {
    "Energy": ["PTT", "GULF", "GPSC", "BGRIM", "EA", "BCP", "EGAT"],
    "Finance": ["BANK", "KBANK", "SCB", "KTB", "TTB", "BAY", "KKP", "KGI"],
    "Commerce": ["CP", "CRC", "HMPRO", "GLOBAL", "DOHOME"],
    "Healthcare": ["BDMS", "BH", "BCH", "CHG", "EKH", "MED"],
    "Telecommunication": ["ADVANC", "TRUE", "INTUCH", "JAS"],
    "Transportation": ["AOT", "BEM", "BTS"],
    "Food": ["CPF", "TU", "OSP", "CBG", "SNNP"],
    "Property": ["REIT", "LAND", "PROP"]
}

In [46]:
#ดึง “เฉพาะหุ้นใหม่” จาก DB
stocks_df = pd.read_sql("""
    SELECT stock_id, symbol
    FROM stocks
    WHERE category_id IS NULL
""", engine)

In [47]:
#เอา symbol ไป classify
stocks_df["category"] = stocks_df["symbol"].apply(classify)

In [48]:
#insert category ลง table (กันซ้ำ)
from sqlalchemy import text

with engine.begin() as conn:
    for cat in stocks_df["category"].unique():
        conn.execute(text("""
            INSERT INTO categories (category_name)
            VALUES (:cat)
            ON CONFLICT (category_name) DO NOTHING
        """), {"cat": cat})

In [49]:
#update stocks → ใส่ category_id
with engine.begin() as conn:
    for _, row in stocks_df.iterrows():
        conn.execute(text("""
            UPDATE stocks
            SET category_id = (
                SELECT category_id
                FROM categories
                WHERE category_name = :category
            )
            WHERE stock_id = :id
        """), {
            "category": row["category"],
            "id": int(row["stock_id"])
        })

In [50]:
#ตรวจสอบผล
pd.read_sql("""
SELECT COUNT(*) 
FROM stocks 
WHERE category_id IS NULL
""", engine)

   count
0      0

In [51]:
pd.read_sql("""
SELECT COUNT(*) AS total_stocks
FROM stocks
""", engine)

   total_stocks
0           870

In [52]:
pd.read_sql("""
SELECT COUNT(*) AS missing_category
FROM stocks
WHERE category_id IS NULL
""", engine)

   missing_category
0                 0

In [53]:
pd.read_sql("""
SELECT c.category_name, COUNT(*) AS total
FROM stocks s
JOIN categories c ON s.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total DESC
""", engine)

       category_name  total
0              Other    794
1             Energy     17
2           Commerce     16
3           Property     12
4               Food      9
5            Finance      8
6         Healthcare      6
7  Telecommunication      4
8     Transportation      4

## รายงานปัญหา  
ตอนนี้มีหลายหุ้นยังไม่สามารถหาประเภทได้ (Other)

## CELL (แก้ไข)

🎯 เป้าหมาย

👉 ลดจำนวน Other โดย “re-classify เฉพาะ Other”

In [54]:
#ดึงเฉพาะ Other

In [55]:
other_df = pd.read_sql("""
SELECT s.stock_id, s.symbol
FROM stocks s
JOIN categories c ON s.category_id = c.category_id
WHERE c.category_name = 'Other'
""", engine)

In [56]:
#ดูตัวอย่างก่อน

In [57]:
other_df.head(20)

    stock_id  symbol
0        199     KCE
1        200     KGI
2        202     KSL
3        204     KTC
4        205  KUMWEL
5        206     L&E
6        207   LANNA
7        208    LHFG
8        209     LIT
9         15     BJC
10        20     CPN
11        22   DELTA
12        29       A
13        30     AAI
14        31     AAV
15        32     ABM
16        33     ACE
17        34     ACG
18        35     ADB
19        36     ADD

In [58]:
#เพิ่ม rule ใหม่ (แก้ไข)

In [14]:
NEW_RULES = {
    "Technology": ["DELTA","KCE","HANA","CCET","SVI","IT","TECH"],
    "Finance": ["KBANK","SCB","KTB","TTB","KTC","KGI","LHFG"],
    "Energy": ["PTT","GULF","GPSC","BGRIM","EA"],
    "Commerce": ["CPALL","CRC","BJC","HMPRO","GLOBAL"],
    "Property": ["CPN","LH","AP","LAND","REIT"],
    "Food": ["CPF","TU","OSP","CBG"],
    "Healthcare": ["BDMS","BH","BCH"],
    "Telecommunication": ["ADVANC","TRUE","INTUCH"],
    "Transportation": ["AOT","AAV","BEM","BTS"]
}

In [15]:
def classify_v2(symbol):
    symbol = symbol.upper()

    # 1. ใช้ rule หลักก่อน
    for category, keywords in NEW_RULES.items():
        if any(k in symbol for k in keywords):
            return category

    # 2. fallback rule (ช่วยลด Other เยอะมาก)
    if any(x in symbol for x in ["REIT", "PROP", "LAND"]):
        return "Property"

    if any(x in symbol for x in ["BANK", "FIN", "CAP", "LEASE"]):
        return "Finance"

    if any(x in symbol for x in ["FOOD", "AGRO", "FARM"]):
        return "Food"

    if any(x in symbol for x in ["TECH", "IT", "SYS"]):
        return "Technology"

    if any(x in symbol for x in ["TRANS", "LOG", "SHIP", "AIR"]):
        return "Transportation"

    # 3. ถ้ายังไม่ได้จริง ๆ
    return "Other"

#  สร้าง function ใหม่
ในขั้นตอนนี้ได้สร้างฟังก์ชัน classify_v2
เพื่อใช้ rule ใหม่ในการจัดหมวดหมู่หุ้น

โดยจะตรวจสอบว่า symbol ของหุ้น
มี keyword ที่ตรงกับ rule หรือไม่

หากพบจะจัดเข้าหมวดที่กำหนด
หากไม่พบจะถูกจัดเป็น "Other"

In [16]:
def classify_v2(symbol):
    symbol = symbol.upper()

    for category, keywords in NEW_RULES.items():
        if any(k in symbol for k in keywords):
            return category

    return "Other"

In [17]:
#test
print(classify_v2("DELTA"))  # ควรได้ Technology
print(classify_v2("KTC"))    # ควรได้ Finance
print(classify_v2("CPN"))    # ควรได้ Property

Technology
Finance
Property

In [6]:
#apply เฉพาะ Other

In [22]:
other_df["new_category"] = other_df["symbol"].apply(classify_v2)

NameError: name 'other_df' is not defined

In [76]:
#ดูผลก่อน update

In [78]:
other_df["new_category"].value_counts()

new_category
Other             778
Property            5
Technology          4
Finance             3
Commerce            2
Transportation      1
Healthcare          1
Name: count, dtype: int64

In [79]:
#ดึงเข้า db
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in other_df.iterrows():
        if row["new_category"] != "Other":
            conn.execute(text("""
                UPDATE stocks
                SET category_id = (
                    SELECT category_id
                    FROM categories
                    WHERE category_name = :category
                )
                WHERE stock_id = :id
            """), {
                "category": row["new_category"],
                "id": int(row["stock_id"])
            })

## จากการทดลองใช้ rule ใหม่ พบว่ายังมีหุ้นจำนวนมาก
ที่ไม่สามารถจัดหมวดหมู่ได้ (Other)

แสดงให้เห็นว่าการใช้ rule ในรอบแรกยังไม่ครอบคลุมเพียงพอ

ดังนั้นจึงต้องใช้วิธี iterative approach โดย:
1. วิเคราะห์หุ้นที่ยังอยู่ในหมวด Other
2. เพิ่ม rule ใหม่จากข้อมูลที่พบ
3. ทำการ re-classify ซ้ำ

กระบวนการนี้จะทำซ้ำหลายรอบ
เพื่อเพิ่มความแม่นยำของการจัดหมวดหมู่