# Step 4 – Store Clean IDX Stock Data into PostgreSQL

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
DB_USER = "postgres"
DB_PASSWORD = "ivan123456"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "idx_bigdata"

engine = create_engine(
    f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)
engine

Engine(postgresql://postgres:***@localhost:5432/idx_bigdata)

In [3]:
df = pd.read_csv("idx_stock_eod_data_clean.csv")
df.head()

,date,open,high,low,close,adjusted_close,volume,warning,symbol
0,2025-02-03,9400,9400,9225,9350,9011.3255,90439906,NaN,BBCA.JK
1,2025-02-03,5975,6000,5700,5800,5165.4765,182181700,NaN,BMRI.JK
2,2025-02-03,2620,2630,2560,2630,2437.9770,91801900,NaN,TLKM.JK
3,2025-02-03,4800,4800,4740,4760,4384.2837,33116100,NaN,ASII.JK
4,2025-02-03,1635,1640,1580,1580,1481.7060,12109000,NaN,UNVR.JK

In [5]:
engine = create_engine(
    "postgresql://postgres:ivan123456@localhost:5432/idx_bigdata"
)
engine

Engine(postgresql://postgres:***@localhost:5432/idx_bigdata)

In [6]:
df.to_sql(
    "idx_stock_eod",
    engine,
    if_exists="replace",
    index=False
)

433

In [7]:
import pandas as pd

query = "SELECT COUNT(*) FROM idx_stock_eod"
pd.read_sql(query, engine)

   count
0   2433