In [1]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:ivan123456@localhost:5432/idx_bigdata"
)

In [2]:
pd.read_sql("SELECT COUNT(*) FROM idx_stock_eod", engine)

   count
0   2433

In [3]:
query = """
SELECT symbol, SUM(volume) AS total_volume
FROM idx_stock_eod
GROUP BY symbol
ORDER BY total_volume DESC
LIMIT 10;
"""
pd.read_sql(query, engine)

    symbol  total_volume
0  BBRI.JK  5.700926e+10
1  BMRI.JK  4.333428e+10
2  ANTM.JK  4.111011e+10
3  BBCA.JK  3.451652e+10
4  TLKM.JK  2.629395e+10
5  ASII.JK  1.093422e+10
6  UNVR.JK  1.086999e+10
7  PGAS.JK  1.051753e+10
8  INDF.JK  2.035158e+09
9  ICBP.JK  1.905626e+09

In [4]:
query = """
SELECT symbol,
       MAX(high) AS max_price,
       MIN(low)  AS min_price
FROM idx_stock_eod
GROUP BY symbol
ORDER BY symbol;
"""
pd.read_sql(query, engine)

    symbol  max_price  min_price
0  ANTM.JK       4970       1355
1  ASII.JK       7475       4370
2  BBCA.JK       9800       6375
3  BBRI.JK       4450       3290
4  BMRI.JK       6000       4010
5  ICBP.JK      12000       7225
6  INDF.JK       8825       6200
7  PGAS.JK       2310       1425
8  TLKM.JK       3990       2050
9  UNVR.JK       2840        985

Conclusion
Data IDX EOD successfully stored in PostgreSQL and queried using SQL.
The analysis shows stock trading activity through volume aggregation
and price range per stock symbol.