## EOD Stock Data Processing

This notebook prepares end-of-day stock price data
for storage and further analysis.

In [1]:
import pandas as pd

In [4]:
from settrade_v2 import Investor
from settrade_v2.market import MarketData

In [8]:
investor = Investor(
    app_id="K2JnAs0pc2Pzi1Pz",
    app_secret="f3myG7DczEPZcE93KKayywR66NQugQ4VpSH0DkJcWxc=",
    app_code="SANDBOX",
    broker_id="SANDBOX"
)

In [9]:
market = investor.MarketData()

In [17]:
market.get_quote_symbol("AOT")

{'instrumentType': 'STOCK',
 'symbol': 'AOT',
 'high': None,
 'low': None,
 'last': None,
 'average': None,
 'change': None,
 'percentChange': None,
 'totalVolume': 0,
 'totalBuyVolume': 0,
 'totalSellVolume': 0,
 'totalNoSideVolume': 0,
 'status': 'S,L',
 'marketStatus': 'Open1',
 'securityType': 'CS',
 'eps': 1.26877,
 'pe': 41.18,
 'pbv': 5.7,
 'percentYield': 1.55,
 'maturityDate': None,
 'exercisePrice': None,
 'underlying': None,
 'underlyingPrice': None,
 'intrinsicValue': None,
 'theoretical': None,
 'moneyness': None,
 'lastTradingDate': None,
 'toLastTrade': None,
 'exerciseRatio': None,
 'impliedVolatility': None,
 'exchange': None,
 'aumSize': None,
 'inav': None}

In [18]:
import pandas as pd

data = market.get_quote_symbol("AOT")
df = pd.DataFrame([data])

df

,instrumentType,symbol,high,low,last,average,change,percentChange,totalVolume,totalBuyVolume,...,intrinsicValue,theoretical,moneyness,lastTradingDate,toLastTrade,exerciseRatio,impliedVolatility,exchange,aumSize,inav
0,STOCK,AOT,None,None,None,None,None,None,0,0,...,None,None,None,None,None,None,None,None,None,None

In [19]:
df_use = df[[
    "symbol",
    "eps",
    "pe",
    "pbv",
    "percentYield",
    "marketStatus"
]]

df_use

  symbol      eps     pe  pbv  percentYield marketStatus
0    AOT  1.26877  41.18  5.7          1.55        Open1